project:
  type: book
  output-dir: _book

metadata-files:
  - ../_shared/common.yml

lang: en

book:
  title: "Ecological Analyses in Julia"
  subtitle: "An introduction to ecological data science with Julia"
  author:
    - name: "Eduardo Santos"
      affiliation: "University of Alberta"
      email: "esantos2@ualberta.ca"
  date: today
  date-format: "YYYY-MM-DD"
  language: en
  search:
    location: sidebar
  sidebar:
    style: docked
  chapters:
    - index.qmd
    - part: "Foundations"
      chapters:
        - 01-introduction.qmd
        - 02-questions.qmd
        - 03-prerequisites.qmd
        - 04-julia-basics.qmd
    - part: "Wrangling and exploring data"
      chapters:
        - 05-tidier.qmd
        - 06-visualization.qmd
        - 07-exploratory.qmd
    - part: "Modelling"
      chapters:
        - 08-linear-models.qmd
        - 09-glm.qmd
    - part: "Programming for ecology"
      chapters:
        - 10-functions.qmd
        - 11-resampling.qmd
    - 99-references.qmd
