{
  "hash": "ac6b7891e380979e5c70b1f54538494f",
  "result": {
    "engine": "julia",
    "markdown": "# Generalized Linear Models {#sec-glm}\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nusing TidierData\nusing DataFrames, CSV\nusing GLM, StatsModels, StatsBase, Statistics, Distributions\nusing MixedModels\nusing CairoMakie\n\nCairoMakie.activate!(type = \"png\")\n\nponds = @chain CSV.read(joinpath(\"..\", \"data\", \"ponds.csv\"), DataFrame) begin\n    @drop_missing(canopy)\n    @mutate(log_area = log(area_m2))\nend\n\nnrow(ponds)\n```\n\n::: {#setup-08 .cell-output .cell-output-display execution_count=1}\n```\n173\n```\n:::\n:::\n\n\n\n\n\n::: {.callout-note .exercise}\n## Exercises in this chapter\n\nAs in @sec-linear-models, you fit a model in each *Your turn* box and pass a number\nextracted from it to `check`. Start each session with:\n\n```julia\ninclude(\"exercises/check.jl\")\nusing TidierData, DataFrames, CSV, GLM, StatsModels, Statistics, MixedModels\nponds = @chain CSV.read(joinpath(\"data\", \"ponds.csv\"), DataFrame) begin\n    @drop_missing(canopy)\n    @mutate(log_area = log(area_m2))\nend\n```\n:::\n\n## Why GLMs in ecology {#sec-why-glm}\n\nCounts are not normal, proportions live in $[0,1]$, presences are binary. The Gaussian\nlinear model treats all of them as if they were continuous and unbounded, and fails in\npredictable ways: confidence intervals that include negative richness, misspecified\nvariance, fan-shaped residuals.\n\nThe GLM fixes this with two choices: the **distribution** of the response and the\n**link function** connecting the mean to the linear predictor.\n\n| Response | Distribution | Link | In Julia |\n|---|---|---|---|\n| Count | Poisson | log | `Poisson(), LogLink()` |\n| Overdispersed count | Negative binomial | log | `negbin(...)` |\n| Presence/absence | Bernoulli/Binomial | logit | `Binomial(), LogitLink()` |\n| Proportion with denominator | Binomial | logit | `Binomial(), LogitLink()` |\n| Positive skewed continuous | Gamma | log | `Gamma(), LogLink()` |\n\n## Poisson: species richness {#sec-poisson}\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ng1 = glm(@formula(richness ~ log_area + canopy + temp_c),\n         ponds, Poisson(), LogLink())\n```\n\n::: {#glm-poisson .cell-output .cell-output-display execution_count=1}\n```\nStatsModels.TableRegressionModel{GeneralizedLinearModel{GLM.GlmResp{Vector{Float64}, Poisson{Float64}, LogLink}, GLM.DensePredChol{Float64, LinearAlgebra.CholeskyPivoted{Float64, Matrix{Float64}, Vector{Int64}}}}, Matrix{Float64}}\n\nrichness ~ 1 + log_area + canopy + temp_c\n\nCoefficients:\n─────────────────────────────────────────────────────────────────────────────\n                  Coef.  Std. Error      z  Pr(>|z|)   Lower 95%    Upper 95%\n─────────────────────────────────────────────────────────────────────────────\n(Intercept)  -0.30001    0.289756    -1.04    0.3005  -0.867921    0.267902\nlog_area      0.331763   0.0300907   11.03    <1e-27   0.272786    0.390739\ncanopy       -0.011555   0.0013362   -8.65    <1e-17  -0.0141739  -0.00893614\ntemp_c        0.0441958  0.00959497   4.61    <1e-05   0.02539     0.0630016\n─────────────────────────────────────────────────────────────────────────────\n```\n:::\n:::\n\n\n\nThe generating process used\n$\\log\\mu = 0.9 + 0.28\\log(\\text{area}) - 0.011\\,\\text{canopy} + 0.03\\,(\\text{temp}-24.5) + \\dots$\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nDataFrame(\n    term      = coefnames(g1),\n    estimated = round.(coef(g1), digits = 4),\n    truth     = [missing, 0.28, -0.011, 0.03],\n)\n```\n\n::: {#poisson-truth .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|ccc}\n\t& term & estimated & truth\\\\\n\t\\hline\n\t& String & Float64 & Float64?\\\\\n\t\\hline\n\t1 & (Intercept) & -0.3 & \\emph{missing} \\\\\n\t2 & log\\_area & 0.3318 & 0.28 \\\\\n\t3 & canopy & -0.0116 & -0.011 \\\\\n\t4 & temp\\_c & 0.0442 & 0.03 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\n::: {.callout-note .exercise}\n## Your turn 9.1 — Adding hydroperiod\n\nFit a Poisson GLM like `g1`, adding `hydro` at the end of the formula. Pass its\ncoefficients to `check(\"9.1\", ...)`, then compare its AIC with that of `g1`.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\nCopy `g1` and add `+ hydro`. `aic(g)` gives the AIC; lower is better.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ng_hydro = glm(@formula(richness ~ log_area + canopy + temp_c + hydro),\n              ponds, Poisson(), LogLink())\ncoef(g_hydro)\n```\n\n::: {#answer-9-1 .cell-output .cell-output-display execution_count=1}\n```\n5-element Vector{Float64}:\n -0.29558194444246627\n  0.3308987450570611\n -0.011543093000739657\n  0.04752717672780725\n -0.18958052468264133\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"9.1\", coef(g_hydro))\n(aic_g1 = aic(g1), aic_hydro = aic(g_hydro))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n\n::: {#answer-9-1-check .cell-output .cell-output-display execution_count=1}\n```\n(aic_g1 = 952.9021516391434, aic_hydro = 944.1070557908266)\n```\n:::\n:::\n\n\n\nThe AIC drops by about 9, so `hydro` earns its place. The simulation added 0.22 to\nthe log mean of permanent ponds; the model estimates −0.19 for temporary ones, the same\neffect seen from the other side.\n:::\n:::\n\n\n\n::: {.callout-tip}\n## Interpreting coefficients on the log scale\n\nA coefficient $\\beta$ under a log link means that a one-unit increase in the predictor\nmultiplies the mean by $e^\\beta$. For `canopy`:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nexp(coef(g1)[3]), (exp(coef(g1)[3]) - 1) * 100\n```\n\n::: {#interpretation .cell-output .cell-output-display execution_count=1}\n```\n(0.9885114593513831, -1.148854064861693)\n```\n:::\n:::\n\n\n\nThat is, each additional percentage point of canopy reduces expected richness by about\n1%.\n:::\n\n::: {.callout-note .exercise}\n## Your turn 9.2 — Temporary ponds, in plain numbers\n\nUsing the model from 9.1, by what factor does expected richness change in a temporary\npond compared with a permanent one, all else equal? Pass that factor to\n`check(\"9.2\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\nThe `hydro: temporary` coefficient is the fifth. Under a log link, a coefficient\n$\\beta$ multiplies the mean by $e^\\beta$.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfactor_temp = exp(coef(g_hydro)[5])\n```\n\n::: {#answer-9-2 .cell-output .cell-output-display execution_count=1}\n```\n0.8273060956543652\n```\n:::\n:::\n\n\n\n::: {#answer-9-2-check .cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"9.2\", factor_temp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n:::\n\n\n\nAbout 0.83: temporary ponds are expected to hold about 17% fewer species than\npermanent ones.\n:::\n:::\n\n\n\n## Overdispersion {#sec-overdispersion}\n\nThe Poisson assumes $\\text{Var}(Y) = \\text{E}(Y)$. Ecological data rarely cooperate.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n# Pearson residual: (y - mu) / sqrt(Var(mu)). For the Poisson, Var(mu) = mu.\nmu = predict(g1)\npearson_res = (ponds.richness .- mu) ./ sqrt.(mu)\ndf_res = dof_residual(g1)\nphi = sum(pearson_res .^ 2) / df_res\n\n(dispersion_statistic = phi,\n verdict = phi > 1.5 ? \"overdispersed\" : \"acceptable\")\n```\n\n::: {#dispersion .cell-output .cell-output-display execution_count=1}\n```\n(dispersion_statistic = 1.9527034194568558, verdict = \"overdispersed\")\n```\n:::\n:::\n\n\n\nIf $\\hat\\phi \\gg 1$, the alternatives are the negative binomial or a mixed model with\nan observation-level random effect.\n\n::: {.callout-important}\n## Overdispersion is a symptom, not a diagnosis\n\n`ponds.csv` was generated as a *pure* Poisson process — there is no extra-Poisson\nvariance in the data-generating code. Yet $\\hat\\phi \\approx 1.95$. Why?\n\nBecause the generating model included a region effect that `g1` omits. Unmodelled\nheterogeneity inflates the dispersion statistic exactly as genuine overdispersion\ndoes, and the statistic cannot tell you which one you have.\n\nThis matters practically: the reflex of reaching for a negative binomial whenever\n$\\hat\\phi > 1.5$ can paper over a missing predictor. Check your model structure\nbefore you change your distribution. The GLMM in @sec-glmm addresses the actual cause\nhere.\n:::\n\n::: {.callout-note .exercise}\n## Your turn 9.3 — Testing the warning\n\nThe box above claims that the overdispersion of `g1` comes from a missing predictor.\nTest it: fit a Poisson GLM with `log_area`, `canopy`, `temp_c`, `hydro` and `region`,\ncompute its dispersion statistic as in the block above, and pass it to\n`check(\"9.3\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\nCopy the dispersion block, replacing `g1` with your model. `predict(g)` gives the\nfitted means.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ng_full = glm(@formula(richness ~ log_area + canopy + temp_c + hydro + region),\n             ponds, Poisson(), LogLink())\n\nmu_full = predict(g_full)\nphi_full = sum(((ponds.richness .- mu_full) ./ sqrt.(mu_full)) .^ 2) /\n           dof_residual(g_full)\n```\n\n::: {#answer-9-3 .cell-output .cell-output-display execution_count=1}\n```\n0.9410041742922783\n```\n:::\n:::\n\n\n\n::: {#answer-9-3-check .cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"9.3\", phi_full)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n:::\n\n\n\nAbout 0.94: with the predictors of the generating model in place, the\n\"overdispersion\" is gone. Adding `hydro` alone (9.1) barely moved it; `region` was the\nmissing piece.\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ng2 = negbin(@formula(richness ~ log_area + canopy + temp_c), ponds, LogLink())\n```\n\n::: {#negbin .cell-output .cell-output-display execution_count=1}\n```\nStatsModels.TableRegressionModel{GeneralizedLinearModel{GLM.GlmResp{Vector{Float64}, NegativeBinomial{Float64}, LogLink}, GLM.DensePredChol{Float64, LinearAlgebra.CholeskyPivoted{Float64, Matrix{Float64}, Vector{Int64}}}}, Matrix{Float64}}\n\nrichness ~ 1 + log_area + canopy + temp_c\n\nCoefficients:\n─────────────────────────────────────────────────────────────────────────────\n                  Coef.  Std. Error      z  Pr(>|z|)   Lower 95%    Upper 95%\n─────────────────────────────────────────────────────────────────────────────\n(Intercept)  -0.165087    0.424739   -0.39    0.6975  -0.997561    0.667387\nlog_area      0.334165    0.0432899   7.72    <1e-13   0.249319    0.419012\ncanopy       -0.0120529   0.0019084  -6.32    <1e-09  -0.0157933  -0.00831254\ntemp_c        0.0391606   0.0141787   2.76    0.0057   0.0113708   0.0669503\n─────────────────────────────────────────────────────────────────────────────\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nDataFrame(\n    model  = [\"Poisson\", \"Negative binomial\"],\n    aic    = round.([aic(g1), aic(g2)], digits = 1),\n    bic    = round.([bic(g1), bic(g2)], digits = 1),\n    loglik = round.([loglikelihood(g1), loglikelihood(g2)], digits = 1),\n)\n```\n\n::: {#poisson-vs-nb .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|cccc}\n\t& model & aic & bic & loglik\\\\\n\t\\hline\n\t& String & Float64 & Float64 & Float64\\\\\n\t\\hline\n\t1 & Poisson & 952.9 & 965.5 & -472.5 \\\\\n\t2 & Negative binomial & 911.3 & 927.0 & -450.6 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\n## Offsets {#sec-offset}\n\nWhen sampling effort varies across units, model the **rate** rather than the raw\ncount, using an offset.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ng3 = glm(@formula(richness ~ canopy + temp_c), ponds, Poisson(), LogLink();\n         offset = log.(ponds.area_m2))\n\ncoeftable(g3)\n```\n\n::: {#offset .cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|             |      Coef. | Std. Error |      z | Pr(>\\|z\\|) |  Lower 95% |  Upper 95% |\n|:------------|-----------:|-----------:|-------:|:-----------|:-----------|-----------:|\n| (Intercept) | -3.56359   | 0.244593   | -14.57 |     <1e-47 | -4.04299   | -3.0842 |\n| canopy      | -0.0151224 | 0.001304   | -11.60 |     <1e-30 | -0.0176782 | -0.0125666 |\n| temp_c      |  0.0310744 | 0.00949171 |   3.27 |     0.0011 |  0.012471  |  0.0496778 |\n:::\n:::\n\n\n\nThis models richness *per unit area*, fixing the `log(area)` coefficient at 1.\n\n## Logistic regression {#sec-logistic}\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ng4 = glm(@formula(focal ~ canopy + temp_c + hydro),\n         ponds, Binomial(), LogitLink())\n```\n\n::: {#glm-logistic .cell-output .cell-output-display execution_count=1}\n```\nStatsModels.TableRegressionModel{GeneralizedLinearModel{GLM.GlmResp{Vector{Float64}, Binomial{Float64}, LogitLink}, GLM.DensePredChol{Float64, LinearAlgebra.CholeskyPivoted{Float64, Matrix{Float64}, Vector{Int64}}}}, Matrix{Float64}}\n\nfocal ~ 1 + canopy + temp_c + hydro\n\nCoefficients:\n────────────────────────────────────────────────────────────────────────────────\n                       Coef.  Std. Error      z  Pr(>|z|)   Lower 95%  Upper 95%\n────────────────────────────────────────────────────────────────────────────────\n(Intercept)       -5.79176    1.6009      -3.62    0.0003  -8.92947    -2.65406\ncanopy             0.0172429  0.00759302   2.27    0.0232   0.0023609   0.032125\ntemp_c             0.209118   0.0616577    3.39    0.0007   0.088271    0.329965\nhydro: temporary  -0.926093   0.338929    -2.73    0.0063  -1.59038    -0.261805\n────────────────────────────────────────────────────────────────────────────────\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nDataFrame(\n    term       = coefnames(g4),\n    coef       = round.(coef(g4), digits = 4),\n    odds_ratio = round.(exp.(coef(g4)), digits = 3),\n    ci_lower   = round.(exp.(confint(g4)[:, 1]), digits = 3),\n    ci_upper   = round.(exp.(confint(g4)[:, 2]), digits = 3),\n)\n```\n\n::: {#odds-ratios .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|ccccc}\n\t& term & coef & odds\\_ratio & ci\\_lower & ci\\_upper\\\\\n\t\\hline\n\t& String & Float64 & Float64 & Float64 & Float64\\\\\n\t\\hline\n\t1 & (Intercept) & -5.7918 & 0.003 & 0.0 & 0.07 \\\\\n\t2 & canopy & 0.0172 & 1.017 & 1.002 & 1.033 \\\\\n\t3 & temp\\_c & 0.2091 & 1.233 & 1.092 & 1.391 \\\\\n\t4 & hydro: temporary & -0.9261 & 0.396 & 0.204 & 0.77 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\n::: {.callout-note .exercise}\n## Your turn 9.4 — Odds for a meaningful change\n\nThe odds ratio for one percentage point of canopy is close to 1, which is hard to\ninterpret. Compute the odds ratio for an increase of **10** percentage points, from\n`g4`, and pass it to `check(\"9.4\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\nTen points multiply the odds by $e^{10\\beta}$, not by $10\\,e^{\\beta}$.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nor_10 = exp(10 * coef(g4)[2])\n```\n\n::: {#answer-9-4 .cell-output .cell-output-display execution_count=1}\n```\n1.1881878414800107\n```\n:::\n:::\n\n\n\n::: {#answer-9-4-check .cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"9.4\", or_10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n:::\n\n\n\nAbout 1.19: each extra 10 points of canopy multiply the odds of finding the focal\nspecies by 1.19, an increase of 19%.\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ngrid = DataFrame(\n    canopy = repeat(range(0, 100, length = 100), 2),\n    temp_c = fill(mean(ponds.temp_c), 200),\n    hydro  = repeat([\"permanent\", \"temporary\"], inner = 100),\n)\ngrid.p = predict(g4, grid)\n\nfig = Figure(size = (700, 430))\nax = Axis(fig[1, 1], xlabel = \"Canopy cover (%)\",\n          ylabel = \"P(occurrence)\", title = \"Focal species\")\n\nfor (h, col) in zip([\"permanent\", \"temporary\"], [:steelblue, :darkorange])\n    sub = grid[grid.hydro .== h, :]\n    lines!(ax, sub.canopy, sub.p, color = col, linewidth = 2.5, label = h)\nend\nscatter!(ax, ponds.canopy, Float64.(ponds.focal), color = (:grey40, 0.25))\naxislegend(ax, position = :lt)\n\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Predicted probability of focal-species occurrence along the canopy gradient.](09-glm_files/figure-pdf/fig-logistic-output-1.png){#fig-logistic width=700 height=430 fig-pos='H'}\n:::\n:::\n\n\n\n::: {.callout-note .exercise}\n## Your turn 9.5 — Predicting a new pond\n\nA temporary pond has 80% canopy and water at 26 °C. According to `g4`, what is the\nprobability of finding the focal species there? Pass it to `check(\"9.5\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\nBuild a one-row `DataFrame` with the columns `canopy`, `temp_c` and `hydro`, and pass\nit to `predict(g4, ...)`, as with `grid` above.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nnew_pond = DataFrame(canopy = [80.0], temp_c = [26.0], hydro = [\"temporary\"])\np_new = predict(g4, new_pond)\n```\n\n::: {#answer-9-5 .cell-output .cell-output-display execution_count=1}\n```\n1-element Vector{Union{Missing, Float64}}:\n 0.5246412509540385\n```\n:::\n:::\n\n\n\n::: {#answer-9-5-check .cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"9.5\", p_new)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n:::\n\n\n\nAbout 0.52. `predict` returns probabilities for a logistic GLM by default: the link\nfunction is undone for you.\n:::\n:::\n\n\n\n## GLMMs {#sec-glmm}\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ngm1 = fit(MixedModel,\n          @formula(richness ~ log_area + canopy + (1 | region)),\n          ponds, Poisson())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\rMinimizing 2    Time: 0:00:00 ( 0.12  s/it)\r\n   objective: 217.73449006691337\r\n\r\rMinimizing 219    Time: 0:00:00 ( 1.90 ms/it)\n```\n:::\n\n::: {#glmm .cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|             |    Est. |     SE |     z |      p | σ_region |\n|:----------- | -------:| ------:| -----:| ------:| --------:|\n| (Intercept) |  0.5195 | 0.2688 |  1.93 | 0.0533 |   0.3534 |\n| log_area    |  0.3702 | 0.0307 | 12.05 | <1e-32 |          |\n| canopy      | -0.0103 | 0.0013 | -7.72 | <1e-13 |          |\n\n:::\n:::\n\n\n\n::: {.r-equivalent}\n**In R**\n\n```r\nglmer(richness ~ log_area + canopy + (1 | region),\n      data = ponds, family = poisson)\n```\n\nThe formula notation is the same, `(1 | group)` included. For the estimation method\nused and the options available, consult the `MixedModels.jl` documentation\n[@mixedmodelsjl]: these are details that change between versions, and not worth\nreproducing here from memory.\n:::\n\n::: {.callout-note .exercise}\n## Your turn 9.6 — A GLMM with hydroperiod\n\nAdd `hydro` to `gm1` and pass the fixed effects of the new model to\n`check(\"9.6\", ...)`. Compare the `hydro` estimate with the one from 9.1.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\nAdd `+ hydro` before the random-effect term. `fixef(gm)` returns the fixed effects.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ngm_hydro = fit(MixedModel,\n               @formula(richness ~ log_area + canopy + hydro + (1 | region)),\n               ponds, Poisson(); progress = false)\nfixef(gm_hydro)\n```\n\n::: {#answer-9-6 .cell-output .cell-output-display execution_count=1}\n```\n4-element Vector{Float64}:\n  0.6010699251615104\n  0.36943180045773477\n -0.010471694153766219\n -0.15989429314658773\n```\n:::\n:::\n\n\n\n::: {#answer-9-6-check .cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"9.6\", fixef(gm_hydro))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n:::\n\n\n:::\n:::\n\n\n\n## Gaps you will hit {#sec-glm-gaps}\n\nThis is the point where being honest is worth more than being enthusiastic. The table\nbelow is an assessment as of **August 2026**, made by checking the public package\nregistries; check before concluding that something does not exist.\n\n| You need | In R | In Julia today |\n|---|---|---|\n| Zero-inflation, hurdle | `glmmTMB`, `pscl` | no mature equivalent |\n| Beta regression | `betareg`, `glmmTMB` | no mature equivalent |\n| Additive models (GAM) | `mgcv` | no mature equivalent |\n| Simulated quantile residuals | `DHARMa` | none; implementable by hand |\n| Marginal means, contrasts | `emmeans` | `Effects.jl`, partial coverage |\n| Ordinal regression | `ordinal`, `MASS::polr` | partial coverage |\n\n### The pragmatic escape hatch: `RCall.jl` {#sec-rcall}\n\nThere is no shame in calling R from inside Julia when the right package only exists\nthere. The workflow stays reproducible, and data crosses the boundary automatically.\n\n::: {#rcall-example .cell execution_count=0}\n``` {.julia .cell-code}\nusing RCall\n\n@rput ponds        # send the DataFrame to R\n\nR\"\"\"\nlibrary(mgcv)\nm <- gam(richness ~ s(canopy) + s(log_area) + region,\n         family = poisson, data = ponds)\nsummary(m)\n\"\"\"\n```\n:::\n\n\n\n::: {.callout-note}\n## Where this leaves you\n\nFor the repertoire covered by this chapter — Poisson, negative binomial, binomial,\ngamma, offsets, GLMMs — Julia covers what you need, and this chapter has demonstrated\nit with executed code. Outside it, `RCall.jl` is the bridge. Naming the boundary\nclearly serves the reader better than hiding it.\n:::\n\n## Challenges {.unnumbered}\n\n1. Compute the dispersion statistic for `g2`. Did the negative binomial fix the\n   overdispersion? After 9.3, would you still choose it?\n2. Build the predicted-probability curve of @fig-logistic for each hydroperiod at three\n   temperatures (22, 24.5 and 27 °C). How much does temperature shift the curve?\n3. Implement `DHARMa`-style quantile residuals for `g1`: simulate 250 datasets from the\n   fitted model and, for each pond, compute the proportion of simulated values below\n   the observed one. If the model is right, these proportions are uniform. Are they?\n   Repeat for the model from 9.3.\n\n",
    "supporting": [
      "09-glm_files/figure-pdf"
    ],
    "filters": []
  }
}