{
  "hash": "4a46638aca21d1dfb9484ef6966497ce",
  "result": {
    "engine": "julia",
    "markdown": "# Resampling and simulation {#sec-resampling}\n\nEvery test in @sec-linear-models and @sec-glm leans on a theoretical distribution: the\n*t*, the normal, the $\\chi^2$. This chapter builds those distributions from the data\ninstead, by shuffling and resampling, and then turns the idea around: simulating data\nfrom a known process to ask how often a study of a given size would find an effect.\n\nJulia is a natural fit. Resampling means running the same calculation thousands of\ntimes, and in Julia the plain loop that expresses the idea is also fast\n(@sec-control), so there is no need to contort the code to avoid it.\n\n::: {.callout-note}\n## Where this chapter comes from\n\nLike @sec-own-functions, this chapter is **inspired by** **ecoR** [@oliveira_ecor],\nthe R course wiki of the Instituto de Biociências, Universidade de São Paulo, produced\nand maintained by Alexandre Adalardo de Oliveira. The sequence — permutation, then\nbootstrap, then simulation from known distributions, with a null model for species\nco-occurrence — follows its resampling module. The text, examples and exercises here\nare written from scratch for Julia; the authors of ecoR have not reviewed this book.\n\nIf you read Portuguese and want to go further, the original material is freely\navailable (CC BY-SA 4.0):\n\n- [8. Reamostragem e Simulação](https://ecor.ib.usp.br/doku.php?id=03_apostila:08-simulacao)\n  — the course notes;\n- [8. Reamostragem e Simulação](https://ecor.ib.usp.br/doku.php?id=02_tutoriais:tutorial9:start)\n  — the step-by-step tutorial;\n- [exercises on resampling](https://ecor.ib.usp.br/doku.php?id=01_curso_atual:exerpermuta),\n  automatically graded in [notaR](http://notar.ib.usp.br), in R;\n- [Simulando Dados](https://ecor.ib.usp.br/doku.php?id=01b_simular:start), a short\n  course on simulating data for linear, mixed and generalized linear models.\n:::\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nusing TidierData\nusing DataFrames, CSV\nusing Statistics, StatsBase, Random, Distributions\nusing GLM, HypothesisTests\nusing CairoMakie\n\nCairoMakie.activate!(type = \"png\")\nRandom.seed!(2026)\n\nponds = @chain CSV.read(joinpath(\"..\", \"data\", \"ponds.csv\"), DataFrame) begin\n    @drop_missing(canopy)\n    @mutate(log_area = log(area_m2))\nend\n\nnrow(ponds)\n```\n\n::: {#setup-10 .cell-output .cell-output-display execution_count=1}\n```\n173\n```\n:::\n:::\n\n\n\n\n\n::: {.callout-note .exercise}\n## Exercises in this chapter\n\nMost answers here come from random draws, so yours will not match the solution to the\nlast digit, and `check` accepts anything within the expected random variation. Use at\nleast as many permutations or simulations as the exercise asks for: with too few, the\nanswer is too noisy to pass. Start each session with:\n\n```julia\ninclude(\"exercises/check.jl\")\nusing TidierData, DataFrames, CSV, Statistics, StatsBase, Random, Distributions\nusing GLM, HypothesisTests\nponds = @chain CSV.read(joinpath(\"data\", \"ponds.csv\"), DataFrame) begin\n    @drop_missing(canopy)\n    @mutate(log_area = log(area_m2))\nend\n```\n:::\n\n## Randomness you can reproduce {#sec-rng}\n\nThree functions do almost all the work in this chapter. `shuffle` reorders a vector;\n`sample`, from `StatsBase.jl`, draws from it with or without replacement:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nx = [1, 2, 3, 4, 5]\n\n(shuffled         = shuffle(x),\n without_replace  = sample(x, 3; replace = false),\n with_replace     = sample(x, 5))              # replace = true is the default\n```\n\n::: {#shuffle-sample .cell-output .cell-output-display execution_count=1}\n```\n(shuffled = [1, 3, 4, 2, 5], without_replace = [2, 4, 5], with_replace = [2, 5, 2, 5, 4])\n```\n:::\n:::\n\n\n\nRandom numbers in Julia come from a **random number generator** (RNG). Setting its\nseed, as the setup block does with `Random.seed!(2026)`, makes a script produce the\nsame draws each time it runs. For code you want to control more tightly, create a\ngenerator of your own and pass it as the first argument:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nrng = Xoshiro(42)\nsample(rng, x, 3)\n```\n\n::: {#rng-object .cell-output .cell-output-display execution_count=1}\n```\n3-element Vector{Int64}:\n 4\n 3\n 3\n```\n:::\n:::\n\n\n\n::: {.callout-warning}\n## Same seed, different Julia, different numbers\n\nThe Julia manual states that a minor release (1.11 to 1.12, say) *may change* the\nsequence of random numbers generated from a given seed. A seed makes your analysis\nreproducible on your setup, not across all versions. For exact reproducibility, save\nthe random data, or pin the Julia version and the `Manifest.toml`. This is also why the\nexercises here accept a range of answers.\n:::\n\n## Permutation tests {#sec-permutation}\n\nIn @sec-tests a Welch *t* test asked whether body size differs between permanent and\ntemporary ponds. A permutation test asks the same question with no distributional\nassumption, in five steps:\n\n1. Choose a statistic that measures the effect: here, the difference in mean body\n   size between permanent and temporary ponds.\n2. Compute it for the real data.\n3. State the null hypothesis as a shuffle: if hydroperiod has no effect, the labels\n   \"permanent\" and \"temporary\" are interchangeable.\n4. Shuffle the labels many times, recomputing the statistic each time. This builds\n   the distribution of the statistic *under the null hypothesis*.\n5. The p-value is the proportion of shuffles with a statistic at least as extreme as\n   the observed one.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nis_perm = ponds.hydro .== \"permanent\"\nmean_diff(y, g) = mean(y[g]) - mean(y[.!g])\n\nobserved = mean_diff(ponds.body_size, is_perm)\n\nB = 9_999\nnull_diffs = zeros(B)\nlabels = copy(is_perm)\nfor b in 1:B\n    shuffle!(labels)                        # step 3–4: shuffle, recompute\n    null_diffs[b] = mean_diff(ponds.body_size, labels)\nend\n\nextreme = count(abs.(null_diffs) .>= abs(observed))\np_perm = (extreme + 1) / (B + 1)\n\n(observed = observed, p_perm = p_perm)\n```\n\n::: {#permutation .cell-output .cell-output-display execution_count=1}\n```\n(observed = -0.8929446693657113, p_perm = 0.1073)\n```\n:::\n:::\n\n\n\nTwo details. `abs` makes the test two-sided: a difference of −0.9 counts as extreme as\none of +0.9. And the `+ 1` in numerator and denominator counts the observed data as\none of the possible arrangements, which keeps the p-value from ever being exactly\nzero [@phipson2010permutation].\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (700, 380))\nax = Axis(fig[1, 1], xlabel = \"Difference in mean body size (mm), permanent − temporary\",\n          ylabel = \"Shuffles\")\nhist!(ax, null_diffs, bins = 50, color = (:grey60, 0.8))\nvlines!(ax, [observed, -observed], color = :darkorange, linestyle = :dash, linewidth = 2)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Null distribution of the difference in mean body size, from 9 999 shuffles of the hydroperiod labels. The dashed lines mark the observed difference and its mirror image.](11-resampling_files/figure-pdf/fig-permutation-output-1.png){#fig-permutation width=700 height=380 fig-pos='H'}\n:::\n:::\n\n\n\nThe p-value, about 0.10, is close to the 0.103 of the Welch test: with 173 ponds and\nroughly symmetric data, the theory and the shuffling agree. That will not always be\ntrue with small samples or skewed data, which is where permutation earns its keep.\n`HypothesisTests.jl` packages the same idea:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nperm_ponds = ponds.body_size[is_perm]\ntemp_ponds = ponds.body_size[.!is_perm]\npvalue(ApproximatePermutationTest(perm_ponds, temp_ponds, mean, 9_999))\n```\n\n::: {#permutation-package .cell-output .cell-output-display execution_count=1}\n```\n0.10461046104610461\n```\n:::\n:::\n\n\n\n::: {.callout-note .exercise}\n## Your turn 11.1 — Canopy and the focal species\n\nIs canopy cover different in ponds where the focal species occurs? Run a two-sided\npermutation test on the difference in mean `canopy` between ponds with `focal == 1`\nand `focal == 0`, with 9 999 shuffles, and pass the p-value to `check(\"11.1\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\nReuse `mean_diff` and the loop above, with `ponds.canopy` as the response and\n`ponds.focal .== 1` as the groups.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nhas_focal = ponds.focal .== 1\nobs_canopy = mean_diff(ponds.canopy, has_focal)\n\ngroups = copy(has_focal)\nnull_canopy = [mean_diff(ponds.canopy, shuffle!(groups)) for _ in 1:9_999]\np_canopy = (count(abs.(null_canopy) .>= abs(obs_canopy)) + 1) / (9_999 + 1)\n```\n\n::: {#answer-11-1 .cell-output .cell-output-display execution_count=1}\n```\n0.0353\n```\n:::\n:::\n\n\n\n::: {#answer-11-1-check .cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"11.1\", p_canopy)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n:::\n\n\n\nAbout 0.04: ponds with the focal species have about 7 points more canopy. The\nsimulation built exactly that in: occurrence rises with canopy (`scripts/make_data.jl`).\nThe comprehension does the same as the loop, in one line.\n:::\n:::\n\n\n\n## Permuting a regression {#sec-permutation-regression}\n\nThe same logic tests a slope. If body size does not depend on canopy, any pairing of\nbody sizes with canopy values is as likely as the observed one, so shuffling the\nresponse breaks the relationship while keeping both distributions intact:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nslope(x, y) = cov(x, y) / var(x)\n\nobs_slope = slope(ponds.canopy, ponds.body_size)\n\ny = copy(ponds.body_size)\nnull_slopes = [slope(ponds.canopy, shuffle!(y)) for _ in 1:9_999]\nextreme = count(abs.(null_slopes) .>= abs(obs_slope))\n\n(slope = obs_slope, extreme = extreme, p = (extreme + 1) / (9_999 + 1))\n```\n\n::: {#permutation-slope .cell-output .cell-output-display execution_count=1}\n```\n(slope = -0.04966562886720384, extreme = 0, p = 0.0001)\n```\n:::\n:::\n\n\n\n`cov(x, y) / var(x)` is the least-squares slope, the same number `lm` estimates in\n@sec-simple-lm. Almost no shuffle produces a slope as steep as the observed one — the\ncount is in `extreme` — so the p-value is at or near the smallest that 9 999 shuffles\ncan show, 1/10 000. To say more you would need more shuffles, but \"about 1 in 10 000\nor less\" is usually all a result needs.\n\n::: {.callout-note .exercise}\n## Your turn 11.2 — Body size and pond area\n\nTest by permutation whether body size is related to pond area: use the slope of\n`body_size` on `log_area`, two-sided, with 9 999 shuffles. Pass the p-value to\n`check(\"11.2\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\nThe block above with `ponds.log_area` in place of `ponds.canopy`. Shuffle a copy of\n`body_size`, not the column itself, so the data stay intact.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nobs_area = slope(ponds.log_area, ponds.body_size)\ny = copy(ponds.body_size)\nnull_area = [slope(ponds.log_area, shuffle!(y)) for _ in 1:9_999]\np_area = (count(abs.(null_area) .>= abs(obs_area)) + 1) / (9_999 + 1)\n```\n\n::: {#answer-11-2 .cell-output .cell-output-display execution_count=1}\n```\n0.2583\n```\n:::\n:::\n\n\n\n::: {#answer-11-2-check .cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"11.2\", p_area)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n:::\n\n\n\nAbout 0.26. The simulation has no effect of area on body size, and the test finds\nnone — correctly, this time. One test in twenty would find one anyway.\n:::\n:::\n\n\n\n## The bootstrap {#sec-bootstrap}\n\nA permutation test asks what the data would look like if there were no effect. The\n**bootstrap** [@efron1979bootstrap] asks a different question: how much would an\nestimate change if we had collected another sample? We cannot collect it, but we can\nimitate it by drawing a new sample of the same size *from the data themselves, with\nreplacement*. Some ponds appear twice, others not at all, and the spread of the\nestimate across many such samples measures its uncertainty.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nn = nrow(ponds)\nboot_medians = [median(sample(ponds.body_size, n)) for _ in 1:9_999]\n\n(median = median(ponds.body_size),\n ci_95  = quantile(boot_medians, [0.025, 0.975]))\n```\n\n::: {#bootstrap-median .cell-output .cell-output-display execution_count=1}\n```\n(median = 35.56, ci_95 = [35.08, 36.54])\n```\n:::\n:::\n\n\n\nThe 2.5% and 97.5% quantiles of the bootstrap medians give a 95% **percentile\ninterval** — for a statistic, the median, that has no simple formula for its standard\nerror.\n\nThe bootstrap also checks a model's own uncertainty. Resample whole ponds (rows), refit\nthe Poisson model `g1` of @sec-poisson each time, and compare the spread of the canopy\ncoefficient with the standard error the model reports:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ng1 = glm(@formula(richness ~ log_area + canopy + temp_c), ponds, Poisson(), LogLink())\n\nboot_canopy = map(1:2_000) do _\n    rows = sample(1:n, n)\n    coef(glm(@formula(richness ~ log_area + canopy + temp_c),\n             ponds[rows, :], Poisson(), LogLink()))[3]\nend\n\n(bootstrap_se = std(boot_canopy),\n model_se     = stderror(g1)[3],\n ratio        = std(boot_canopy) / stderror(g1)[3])\n```\n\n::: {#bootstrap-glm .cell-output .cell-output-display execution_count=1}\n```\n(bootstrap_se = 0.0018378945669366084, model_se = 0.0013361976263705476, ratio = 1.3754661216760258)\n```\n:::\n:::\n\n\n\nThe bootstrap standard error is about 1.4 times larger than the one the Poisson model\nreports — close to $\\sqrt{1.95}$, the square root of the dispersion statistic of `g1`\nin @sec-overdispersion. The model's standard errors assume the variance equals the\nmean; the bootstrap assumes nothing about it, and sees the extra variation the model\nleaves out.\n\n::: {.callout-tip}\n## `do` blocks\n\n`map(1:2_000) do _ ... end` is `map(_ -> ..., 1:2_000)` written as a block, for\nanonymous functions longer than one line. `_` names an argument you do not use.\n:::\n\n::: {.callout-note .exercise}\n## Your turn 11.3 — A bootstrap function\n\nWrite `boot_means(x, B)`, which returns a vector with the means of `B` bootstrap\nsamples of `x`. Check it with `check(\"11.3\", boot_means)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\nOne comprehension: `[mean(sample(x, length(x))) for _ in 1:B]`. Each bootstrap sample\nhas the same size as `x` and is drawn with replacement.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {#answer-11-3 .cell execution_count=1}\n``` {.julia .cell-code}\nboot_means(x, B) = [mean(sample(x, length(x))) for _ in 1:B]\n\ncheck(\"11.3\", boot_means)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n:::\n\n\n:::\n:::\n\n\n\n::: {.callout-note .exercise}\n## Your turn 11.4 — How rich are Amazonian ponds?\n\nUsing `boot_means` with 9 999 samples, compute a 95% percentile interval for the mean\nrichness of the Amazon ponds. Pass it as `[lower, upper]` to `check(\"11.4\", ...)`.\nCompare it with the usual *t* interval.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\n`ponds.richness[ponds.region .== \"Amazon\"]` selects the Amazon ponds. `quantile(v,\n[0.025, 0.975])` returns both ends at once.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\namazon = ponds.richness[ponds.region .== \"Amazon\"]\nci_boot = quantile(boot_means(amazon, 9_999), [0.025, 0.975])\n```\n\n::: {#answer-11-4 .cell-output .cell-output-display execution_count=1}\n```\n2-element Vector{Float64}:\n  9.478260869565217\n 12.956521739130435\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"11.4\", ci_boot)\nconfint(OneSampleTTest(amazon))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n\n::: {#answer-11-4-check .cell-output .cell-output-display execution_count=1}\n```\n(9.384117221613428, 12.963708865343095)\n```\n:::\n:::\n\n\n\nThe two intervals nearly coincide, from about 9.4–9.5 to 13. The bootstrap one starts\na little higher: richness is a skewed count, and the bootstrap follows the skew where\nthe *t* interval is symmetric by construction.\n:::\n:::\n\n\n\n## How many ponds do I need? {#sec-power}\n\nResampling reuses the data you have. Simulation creates data you do not have yet, from\na process you specify — and because you chose the process, you know the right answer.\nThat is the logic of this whole book (@sec-pond-data), and it answers a question every\nfield project faces before it starts: **how many sampling units are enough?**\n\nSuppose permanent ponds hold about 25% more species than temporary ones, as in the\nsimulation behind `ponds.csv` ($e^{0.22} \\approx 1.25$). This function generates a\nsurvey of `n` ponds from that process:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfunction simulate_ponds(n; p_temporary = 0.5, rng = Random.default_rng())\n    log_area = rand(rng, Normal(5.0, 0.9), n)\n    hydro    = ifelse.(rand(rng, n) .< p_temporary, \"temporary\", \"permanent\")\n    mu       = @. exp(0.9 + 0.28 * log_area + 0.22 * (hydro == \"permanent\"))\n    richness = rand.(rng, Poisson.(mu))\n    return DataFrame(; log_area, hydro, richness)\nend\n\nfirst(simulate_ponds(5), 5)\n```\n\n::: {#simulate-ponds .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|ccc}\n\t& log\\_area & hydro & richness\\\\\n\t\\hline\n\t& Float64 & String & Int64\\\\\n\t\\hline\n\t1 & 4.34568 & temporary & 13 \\\\\n\t2 & 6.30406 & permanent & 18 \\\\\n\t3 & 5.49257 & temporary & 12 \\\\\n\t4 & 4.17274 & permanent & 7 \\\\\n\t5 & 4.56875 & permanent & 9 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\nFor a survey of `n` ponds, fit the model and record whether it detects the effect of\nhydroperiod at the 5% level. The proportion of simulated surveys that do is the\n**power** of that design:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfunction detects_hydro(n; kwargs...)\n    d = simulate_ponds(n; kwargs...)\n    m = glm(@formula(richness ~ log_area + hydro), d, Poisson(), LogLink())\n    return coeftable(m).cols[4][3] < 0.05       # p-value of the hydro coefficient\nend\n\nsizes = [20, 40, 60, 80, 100, 140, 180]\npower = [mean(detects_hydro(n) for _ in 1:500) for n in sizes]\n\nDataFrame(n = sizes, power = power)\n```\n\n::: {#power .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|cc}\n\t& n & power\\\\\n\t\\hline\n\t& Int64 & Float64\\\\\n\t\\hline\n\t1 & 20 & 0.35 \\\\\n\t2 & 40 & 0.616 \\\\\n\t3 & 60 & 0.796 \\\\\n\t4 & 80 & 0.886 \\\\\n\t5 & 100 & 0.954 \\\\\n\t6 & 140 & 0.992 \\\\\n\t7 & 180 & 1.0 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (700, 380))\nax = Axis(fig[1, 1], xlabel = \"Number of ponds\", ylabel = \"Power\")\nlines!(ax, sizes, power, color = :steelblue, linewidth = 2.5)\nscatter!(ax, sizes, power, color = :steelblue)\nhlines!(ax, 0.8, color = :grey40, linestyle = :dash)\nylims!(ax, 0, 1)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Power to detect a 25% difference in richness between permanent and temporary ponds, from 500 simulated surveys per sample size. The dashed line marks the conventional target of 80%.](11-resampling_files/figure-pdf/fig-power-output-1.png){#fig-power width=700 height=380 fig-pos='H'}\n:::\n:::\n\n\n\nAbout 60 ponds reach the usual 80% power; with 20, two surveys in three would miss an\neffect that is really there. And a non-significant result from a small survey says\nlittle: most of them are non-significant whether or not the effect exists.\n\n::: {.callout-note .exercise}\n## Your turn 11.5 — When the design is unbalanced\n\nIn the field you rarely get equal numbers of each kind of pond. Estimate the power\nwith 60 ponds when only 20% are temporary (`p_temporary = 0.2`), from at least 1 000\nsimulated surveys, and pass it to `check(\"11.5\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\n`detects_hydro` passes its keywords on to `simulate_ponds` (@sec-fn-arguments), so\n`detects_hydro(60; p_temporary = 0.2)` already does what you need.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\npower_unbalanced = mean(detects_hydro(60; p_temporary = 0.2) for _ in 1:2_000)\n```\n\n::: {#answer-11-5 .cell-output .cell-output-display execution_count=1}\n```\n0.5885\n```\n:::\n:::\n\n\n\n::: {#answer-11-5-check .cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"11.5\", power_unbalanced)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n:::\n\n\n\nAbout 0.60, down from 0.80 with a balanced design: the same 60 ponds tell you less,\nbecause the comparison rests on only about 12 temporary ones.\n:::\n:::\n\n\n\n## A null model for species co-occurrence {#sec-null-model}\n\nPermutation is also the basis of **null models** in community ecology. The question\nhere is whether species co-occur less than expected by chance, which could indicate\ncompetition or different habitat requirements. The data are a presence–absence matrix,\none row per species and one column per site.\n\n`ponds.csv` has no species lists, so this section uses a small matrix simulated for the\npurpose: six species in twelve ponds.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nM = [1 1 1 0 1 1 0 0 0 0 0 1;\n     1 0 1 1 1 1 0 1 0 0 0 0;\n     0 1 1 1 1 1 0 0 0 1 0 0;\n     1 0 0 0 0 0 1 1 1 0 1 1;\n     0 0 1 0 0 0 1 1 0 1 1 1;\n     0 1 0 0 0 0 1 0 1 1 1 1]\n\n(species_occurrences = vec(sum(M, dims = 2)),\n pond_richness       = vec(sum(M, dims = 1)))\n```\n\n::: {#cooccurrence-matrix .cell-output .cell-output-display execution_count=1}\n```\n(species_occurrences = [6, 6, 6, 6, 6, 6], pond_richness = [3, 3, 4, 2, 3, 3, 3, 3, 2, 3, 3, 4])\n```\n:::\n:::\n\n\n\nA common statistic is the **C-score** [@stone1990checkerboard]. For each pair of\nspecies, count the \"checkerboard units\": with $r_i$ and $r_j$ the number of sites each\noccupies and $S$ the number of sites they share, the pair contributes\n$(r_i - S)(r_j - S)$. The C-score is the mean over all pairs. The less species share\nsites, the higher it is.\n\n::: {.callout-note .exercise}\n## Your turn 11.6 — The C-score\n\nWrite `cscore(M)` for a matrix with species in rows and sites in columns, and check\nit with `check(\"11.6\", cscore)`. The rest of this section uses it.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\n`r = vec(sum(M, dims = 2))` gives the occurrences of each species. Loop over pairs\nwith `for i in 1:s-1, j in i+1:s`, where `s = size(M, 1)`; the shared sites are\n`sum(M[i, :] .& M[j, :])`.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfunction cscore(M)\n    r = vec(sum(M, dims = 2))\n    s = size(M, 1)\n    total, pairs = 0.0, 0\n    for i in 1:s-1, j in i+1:s\n        shared = sum(M[i, :] .& M[j, :])\n        total += (r[i] - shared) * (r[j] - shared)\n        pairs += 1\n    end\n    return total / pairs\nend\n\ncscore(M)\n```\n\n::: {#answer-11-6 .cell-output .cell-output-display execution_count=1}\n```\n13.866666666666667\n```\n:::\n:::\n\n\n\n::: {#answer-11-6-check .cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"11.6\", cscore)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n:::\n\n\n:::\n:::\n\n\n\nIs a C-score of about 13.9 high? It depends on what random\nassemblages *of these species in these ponds* would give. Common species share more\nsites than rare ones by chance alone, and rich ponds hold more species than poor ones,\nso a fair null model keeps both the number of occurrences of each species and the\nrichness of each pond fixed, and randomizes only which species go where\n[@gotelli2000null].\n\nThe **swap** algorithm does exactly that. It picks two species and two ponds at\nrandom; if they form a checkerboard — `[1 0; 0 1]` or `[0 1; 1 0]` — it flips it.\nRows and column totals never change:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfunction swap!(M; attempts = 1_000)\n    nsp, nsites = size(M)\n    for _ in 1:attempts\n        i, j = sample(1:nsp, 2; replace = false)\n        k, l = sample(1:nsites, 2; replace = false)\n        if M[i, k] == M[j, l] && M[i, l] == M[j, k] && M[i, k] != M[i, l]\n            M[i, k], M[i, l] = M[i, l], M[i, k]\n            M[j, k], M[j, l] = M[j, l], M[j, k]\n        end\n    end\n    return M\nend\n\nnull_c = [cscore(swap!(copy(M))) for _ in 1:999]\n\nobs_c = cscore(M)\n(observed = obs_c,\n null_mean = mean(null_c),\n p = (count(null_c .>= obs_c) + 1) / (999 + 1),\n ses = (obs_c - mean(null_c)) / std(null_c))\n```\n\n::: {#swap .cell-output .cell-output-display execution_count=1}\n```\n(observed = 13.866666666666667, null_mean = 12.801067734401064, p = 0.011, ses = 3.354757592537985)\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (700, 380))\nax = Axis(fig[1, 1], xlabel = \"C-score\", ylabel = \"Null assemblages\")\nhist!(ax, null_c, bins = 25, color = (:grey60, 0.8))\nvlines!(ax, obs_c, color = :darkorange, linestyle = :dash, linewidth = 2)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![C-scores of 999 null assemblages with the same species frequencies and pond richness as the observed one. The dashed line marks the observed C-score.](11-resampling_files/figure-pdf/fig-null-model-output-1.png){#fig-null-model width=700 height=380 fig-pos='H'}\n:::\n:::\n\n\n\nThe observed C-score sits in the upper tail: about 1% of null assemblages are as\nsegregated. The test is one-sided, because the question was about *less*\nco-occurrence than expected. The **standardized effect size** (`ses`), the distance\nfrom the null mean in null standard deviations, is the usual way to compare such\nresults between matrices of different sizes.\n\n::: {.callout-tip}\n## Doing this for real\n\nThis is a teaching version. For a real analysis, R's `vegan` package (`nullmodel`,\n`oecosimu`) implements many null algorithms with the care they need — including how\nmany swaps are enough for the null matrices to be independent, which this version\nglosses over. @sec-rcall shows how to call it from Julia.\n:::\n\n## Challenges {.unnumbered}\n\n1. Repeat the permutation test of @sec-permutation with `median` instead of `mean` as\n   the statistic. Which would you report for body size, and why?\n2. Rerun the power analysis for a 10% effect ($e^{\\beta} = 1.10$). How many ponds\n   would you need? What would you tell a colleague planning a survey of 40 ponds?\n3. Build a matrix in which only *one* pair of species is perfectly segregated and the\n   others are scattered at random. Does the fixed–fixed null model detect it? What does\n   that say about the C-score as a measure of a single pair's interaction?\n\n",
    "supporting": [
      "11-resampling_files/figure-pdf"
    ],
    "filters": []
  }
}