{
  "hash": "d47b23709e030d9007b2f12fe7059ab6",
  "result": {
    "engine": "julia",
    "markdown": "# Análise exploratória de dados {#sec-exploratoria}\n\nAntes de qualquer modelo, olhe os dados. A exploração tem quatro tarefas\n[@zuur2010protocol]: encontrar **erros e outliers**, entender a **estrutura** dos\ndados — o que conta como réplica —, ver as **distribuições** que os modelos terão de\ndescrever e detectar **colinearidade** entre variáveis que um modelo terá dificuldade\nem separar. Pular essa etapa não economiza tempo: os problemas continuam lá, e aparecem\ndepois como resultados estranhos de modelo.\n\nAs lagoas simuladas dos capítulos anteriores são limpas demais para isso. Este capítulo\nusa dados reais, com todos os problemas que dados reais têm.\n\n::: {.callout-note}\n## De onde vem este capítulo\n\nComo o @sec-funcoes-proprias e o @sec-reamostragem, este capítulo é **inspirado** no\n**ecoR** [@oliveira_ecor], o wiki do curso de R do Instituto de Biociências da\nUniversidade de São Paulo, produzido e mantido por Alexandre Adalardo de Oliveira. A\nsequência — conferir o data frame, estatísticas descritivas, gráficos univariados,\nrelações entre variáveis e o quarteto de Anscombe — segue o módulo de análise\nexploratória do ecoR. O texto, os dados, os exemplos e os exercícios daqui foram\nescritos do zero para Julia; os autores do ecoR não revisaram este livro.\n\nSe quiser ir além, o material original está disponível gratuitamente (CC BY-SA 4.0):\n\n- [4. Análise Exploratória de Dados](https://ecor.ib.usp.br/doku.php?id=03_apostila:05-exploratoria)\n  — a apostila;\n- [4. Tutoriais de Análise Exploratória de Dados](https://ecor.ib.usp.br/doku.php?id=02_tutoriais:tutorial4:start)\n  — o tutorial passo a passo;\n- [exercícios de análise exploratória](https://ecor.ib.usp.br/doku.php?id=01_curso_atual:exercicios4),\n  corrigidos automaticamente no [notaR](http://notar.ib.usp.br), em R.\n:::\n\n::: {.callout-note}\n## Os dados: ATLANTIC BIRD TRAITS\n\nO **ATLANTIC BIRD TRAITS** [@rodrigues2019atlantic] reúne medidas morfológicas de aves\ndas florestas atlânticas da América do Sul: 72 483 registros, compilados de coleções de\nmuseu, projetos de anilhamento e da literatura entre 1820 e 2018, por 179 autores. O\nartigo de dados afirma que não há restrições de direitos autorais nem de propriedade\nsobre o seu uso, e pede que seja citado quando usado em publicações ou no ensino — como\naqui.\n\nO `data/atlantic_bird_traits.csv` mantém **todos** os registros e 21 das 83 colunas\noriginais, com os nomes e códigos originais. Nada foi limpo: encontrar os problemas é o\nobjetivo. O `scripts/prepare_birds.jl` documenta como o subconjunto foi feito a partir\ndo arquivo original, que está no material suplementar do artigo.\n:::\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nusing TidierData\nusing DataFrames, CSV\nusing Statistics, StatsBase\nusing GLM, RDatasets, Distributions\nusing CairoMakie\n\nCairoMakie.activate!(type = \"png\")\narquivo_aves = joinpath(\"..\", \"data\", \"atlantic_bird_traits.csv\")\n```\n\n::: {#setup-07 .cell-output .cell-output-display execution_count=1}\n```\n\"../data/atlantic_bird_traits.csv\"\n```\n:::\n:::\n\n\n\n\n\n::: {.callout-note .exercise}\n## Exercícios deste capítulo\n\nAs respostas são números calculados a partir dos dados das aves. Comece cada sessão\ncom:\n\n```julia\ninclude(\"exercises/checar.jl\")\nusing TidierData, DataFrames, CSV, Statistics, StatsBase, GLM, Distributions\narquivo_aves = joinpath(\"data\", \"atlantic_bird_traits.csv\")\n```\n\nA primeira seção mostra como ler o arquivo; os exercícios seguintes supõem que você o\nleu desse jeito, em `birds`, com as colunas renomeadas.\n:::\n\n## Primeiro contato: lendo o arquivo {#sec-eda-leitura}\n\nLeia o arquivo como ele vem e olhe o tipo de cada coluna:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nbruto = CSV.read(arquivo_aves, DataFrame)\nsize(bruto)\n```\n\n::: {#read-naive .cell-output .cell-output-display execution_count=1}\n```\n(72483, 21)\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfirst(describe(bruto, :eltype, :nmissing), 8)\n```\n\n::: {#types-naive .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|ccc}\n\t& variable & eltype & nmissing\\\\\n\t\\hline\n\t& Symbol & DataType & Int64\\\\\n\t\\hline\n\t1 & ID\\_ABT & String7 & 0 \\\\\n\t2 & Order & String31 & 0 \\\\\n\t3 & Family & String31 & 0 \\\\\n\t4 & Binomial & String31 & 0 \\\\\n\t5 & Body\\_mass.g. & String7 & 0 \\\\\n\t6 & Wing\\_length.mm. & String7 & 0 \\\\\n\t7 & Tail\\_length.mm. & String7 & 0 \\\\\n\t8 & Tarsus\\_length.mm. & String7 & 0 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\nMassa corporal, comprimento da asa, comprimento da cauda: tudo lido como **texto**\n(`String`), e nenhum valor faltante. O motivo está no próprio arquivo — os valores\nfaltantes estão escritos como as duas letras `NA`, que o `CSV.jl` não trata como\nfaltante por padrão. Um único não número em uma coluna faz a coluna inteira virar\ntexto. Diga ao `CSV.read` qual código significa faltante:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nbirds = CSV.read(arquivo_aves, DataFrame; missingstring = \"NA\")\nfirst(describe(birds, :eltype, :nmissing), 8)\n```\n\n::: {#read-na .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|ccc}\n\t& variable & eltype & nmissing\\\\\n\t\\hline\n\t& Symbol & Type & Int64\\\\\n\t\\hline\n\t1 & ID\\_ABT & String7 & 0 \\\\\n\t2 & Order & String31 & 0 \\\\\n\t3 & Family & String31 & 0 \\\\\n\t4 & Binomial & String31 & 0 \\\\\n\t5 & Body\\_mass.g. & Union\\{Missing, Float64\\} & 11664 \\\\\n\t6 & Wing\\_length.mm. & Union\\{Missing, Float64\\} & 51134 \\\\\n\t7 & Tail\\_length.mm. & Union\\{Missing, Float64\\} & 26183 \\\\\n\t8 & Tarsus\\_length.mm. & Union\\{Missing, Float64\\} & 50742 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\n::: {.r-equivalent}\n**Em R**\n\nO `read.csv` trata `\"NA\"` como faltante por padrão, então em R esse problema passaria\ndespercebido. Aqui ele fica visível: uma coluna numérica que chega como texto é o\nprimeiro sinal de que o arquivo usa um código de faltante que você não declarou. Outros\ncódigos comuns são `\"\"`, `\"-\"`, `\".\"`, `-999` e `99999`; `missingstring` também aceita\num vetor deles.\n:::\n\nOs nomes das colunas misturam unidades, pontos e maiúsculas, como `Body_mass.g.`. São\nincômodos de digitar, e as macros do Tidier não conseguem usá-los diretamente.\nRenomeie-os uma vez, no início:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nrename!(birds,\n    \"ID_ABT\" => :id, \"Order\" => :order, \"Family\" => :family, \"Binomial\" => :species,\n    \"Body_mass.g.\" => :mass_g, \"Wing_length.mm.\" => :wing_mm,\n    \"Tail_length.mm.\" => :tail_mm, \"Tarsus_length.mm.\" => :tarsus_mm,\n    \"Bill_length.mm.\" => :bill_mm, \"Age\" => :age, \"Sex\" => :sex, \"Status\" => :status,\n    \"Recapture\" => :recapture, \"Ring\" => :ring,\n    \"Latitude_decimal_degrees\" => :lat, \"Longitude_decimal_degrees\" => :lon,\n    \"Altitude\" => :altitude, \"Year\" => :year, \"Main_researcher\" => :source,\n    \"Outside.range\" => :outside_range, \"Obs.spp\" => :species_note)\n\nnames(birds)\n```\n\n::: {#rename .cell-output .cell-output-display execution_count=1}\n```\n21-element Vector{String}:\n \"id\"\n \"order\"\n \"family\"\n \"species\"\n \"mass_g\"\n \"wing_mm\"\n \"tail_mm\"\n \"tarsus_mm\"\n \"bill_mm\"\n \"age\"\n ⋮\n \"recapture\"\n \"ring\"\n \"lat\"\n \"lon\"\n \"altitude\"\n \"year\"\n \"source\"\n \"outside_range\"\n \"species_note\"\n```\n:::\n:::\n\n\n\nOs nomes novos ficam em inglês, como as colunas dos dados das lagoas, para que o código\nseja o mesmo nas duas versões do livro.\n\n::: {.callout-note .exercise}\n## Sua vez 7.1 — Quantas aves foram pesadas?\n\nQuantos registros têm massa corporal? Passe o número para `checar(\"7.1\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Dica\n\n`count(!ismissing, v)` conta os valores não faltantes de um vetor. Isso só faz sentido\ndepois que o arquivo foi lido com `missingstring = \"NA\"`.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solução\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nn_massa = count(!ismissing, birds.mass_g)\n```\n\n::: {#answer-7-1 .cell-output .cell-output-display execution_count=1}\n```\n60819\n```\n:::\n:::\n\n\n\n::: {#answer-7-1-check .cell execution_count=1}\n``` {.julia .cell-code}\nchecar(\"7.1\", n_massa)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correto!\n```\n:::\n:::\n\n\n\n60 819 de 72 483: a massa corporal é o atributo mais registrado, e ainda assim falta em\num de cada seis registros.\n:::\n:::\n\n\n\n## Faltante, desconhecido e inconsistente {#sec-eda-codigos}\n\nColunas categóricas merecem, antes de tudo, uma tabela dos seus níveis:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n(idade = countmap(birds.age), sexo = countmap(birds.sex))\n```\n\n::: {#levels-age-sex .cell-output .cell-output-display execution_count=1}\n```\n(idade = Dict{Union{Missing, String15}, Int64}(missing => 4935, String15(\"Juvenile\") => 8708, String15(\"Adult\") => 52111, String15(\"Unknown\") => 6727, String15(\"Nestling\") => 2), sexo = Dict{Union{Missing, String7}, Int64}(String7(\"Female\") => 14586, missing => 3072, String7(\"Male\") => 18420, String7(\"Unknown\") => 36405))\n```\n:::\n:::\n\n\n\nHá **dois tipos de faltante** aqui. `missing` quer dizer que a informação nunca foi\nanotada; `\"Unknown\"` quer dizer que alguém olhou a ave e não conseguiu determinar. Não é\na mesma coisa: um estudo de razão sexual deve contar os desconhecidos, mas não os não\nanotados.\n\nOutras colunas discordam de si mesmas na grafia:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n(recaptura = countmap(birds.recapture), fora_distribuicao = countmap(birds.outside_range))\n```\n\n::: {#levels-case .cell-output .cell-output-display execution_count=1}\n```\n(recaptura = Dict{Union{Missing, String3}, Int64}(missing => 33682, String3(\"Yes\") => 8556, String3(\"no\") => 30245), fora_distribuicao = Dict{String3, Int64}(\"Yes\" => 2725, \"no\" => 69758))\n```\n:::\n:::\n\n\n\n`\"no\"` e `\"Yes\"`: a capitalização muda entre os níveis. Aqui isso é inofensivo, porque\ncada nível tem uma única grafia, mas um único `\"yes\"` em algum lugar criaria um terceiro\nnível, que o agrupamento trataria como diferente. Padronizar custa pouco:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nbirds.recapture     = passmissing(lowercase).(birds.recapture)\nbirds.outside_range = lowercase.(birds.outside_range)\nunique(birds.recapture)\n```\n\n::: {#normalize .cell-output .cell-output-display execution_count=1}\n```\n3-element Vector{Union{Missing, String}}:\n \"no\"\n missing\n \"yes\"\n```\n:::\n:::\n\n\n\n`passmissing(f)` aplica `f` aos valores e deixa `missing` em paz.\n\n::: {.callout-note .exercise}\n## Sua vez 7.2 — Com que frequência dá para saber o sexo?\n\nEntre os registros em que o sexo foi **anotado** (não `missing`), que proporção foi\nsexada como `\"Male\"` ou `\"Female\"`? Passe-a para `checar(\"7.2\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Dica\n\nFique com os valores não faltantes com `collect(skipmissing(birds.sex))` e tire a média\nde `in((\"Male\", \"Female\")).(...)`.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solução\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsexo_anotado = collect(skipmissing(birds.sex))\np_sexado = mean(in((\"Male\", \"Female\")).(sexo_anotado))\n```\n\n::: {#answer-7-2 .cell-output .cell-output-display execution_count=1}\n```\n0.47551540822059907\n```\n:::\n:::\n\n\n\n::: {#answer-7-2-check .cell execution_count=1}\n``` {.julia .cell-code}\nchecar(\"7.2\", p_sexado)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correto!\n```\n:::\n:::\n\n\n\nMenos da metade: muitos passeriformes da Mata Atlântica não podem ser sexados na mão.\nQualquer análise por sexo é uma análise de uma metade não aleatória dos dados.\n:::\n:::\n\n\n\n## Estrutura: o que é uma réplica? {#sec-eda-estrutura}\n\nUma linha é um registro, mas registros não são observações independentes. Eles estão\nagrupados de várias formas ao mesmo tempo.\n\n**Por espécie.** Os registros estão muito desigualmente distribuídos:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\npor_especie = sort(combine(groupby(birds, :species), nrow => :n), :n, rev = true)\n\n(nomes = nrow(por_especie),\n cinco_mais = first(por_especie, 5),\n com_um_registro = count(==(1), por_especie.n))\n```\n\n::: {#per-species .cell-output .cell-output-display execution_count=1}\n```\n(nomes = 780, cinco_mais = 5×2 DataFrame\n Row │ species                   n     \n     │ String31                  Int64 \n─────┼─────────────────────────────────\n   1 │ Chiroxiphia caudata        1857\n   2 │ Turdus albicollis          1686\n   3 │ Trichothraupis melanops    1493\n   4 │ Turdus leucomelas          1475\n   5 │ Basileuterus culicivorus   1419, com_um_registro = 68)\n```\n:::\n:::\n\n\n\n780 nomes — alguns identificados só até gênero, como `Elaenia sp.` —, enquanto o artigo\nde dados relata 711 espécies. Antes de contar espécies, decida o que conta como uma. As\ndez espécies mais registradas concentram um quinto de todos os registros; 68 nomes\naparecem uma única vez.\n\n**Por indivíduo.** Uma ave anilhada capturada de novo aparece de novo:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nanilhados = dropmissing(birds[:, [:ring, :species]], :ring)\npor_anilha = combine(groupby(anilhados, :ring),\n                     :species => (s -> length(unique(s))) => :n_species, nrow => :n)\nfirst(sort(por_anilha[por_anilha.n_species .> 1, :], :n, rev = true), 6)\n```\n\n::: {#rings .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|ccc}\n\t& ring & n\\_species & n\\\\\n\t\\hline\n\t& String31 & Int64 & Int64\\\\\n\t\\hline\n\t1 & BRD & 25 & 31 \\\\\n\t2 & VRD & 24 & 27 \\\\\n\t3 & AZD & 21 & 26 \\\\\n\t4 & AZE & 22 & 24 \\\\\n\t5 & IND1 & 4 & 15 \\\\\n\t6 & BRE & 14 & 14 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\nAlgumas \"anilhas\" são compartilhadas por mais de vinte espécies. Não são números de\nanilha, e sim **códigos de anilhas coloridas**, como `BRD` ou `BLUE RIGHT`, que muitas\naves carregam. Uma contagem ingênua de recapturas tomaria todas essas aves por um único\nindivíduo.\n\n**Por fonte e método.** Cada registro vem de um de 65 pesquisadores principais, e de\naves vivas ou peles de museu, ao longo de dois séculos:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncombine(groupby(dropmissing(birds[:, [:status, :year]]), :status),\n        nrow => :n, :year => minimum => :primeiro, :year => median => :mediana,\n        :year => maximum => :ultimo)\n```\n\n::: {#status-year .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|ccccc}\n\t& status & n & primeiro & mediana & ultimo\\\\\n\t\\hline\n\t& String7 & Int64 & Int64 & Float64 & Int64\\\\\n\t\\hline\n\t1 & live & 57862 & 1990 & 2010.0 & 2018 \\\\\n\t2 & museum & 11152 & 1820 & 2007.0 & 2017 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\nCada um desses agrupamentos pode tornar os registros de um mesmo grupo mais parecidos\nentre si do que registros de grupos diferentes — a dependência que os modelos mistos da\n@sec-modelos-mistos levam em conta. Explorar a estrutura diz quais termos de\nagrupamento um modelo precisa.\n\n::: {.callout-note .exercise}\n## Sua vez 7.3 — Quantas aves foram capturadas duas vezes?\n\nConte os indivíduos registrados mais de uma vez: anilhas que aparecem em mais de um\nregistro **da mesma espécie**, ignorando os códigos feitos só de letras (anilhas\ncoloridas). Passe o número para `checar(\"7.3\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Dica\n\nDescarte os códigos só de letras com `occursin(r\"^[A-Za-z]+$\", ring)`, que dá `true`\npara eles. Depois agrupe por `ring` **e** `species`, conte as linhas e conte os grupos\ncom mais de uma.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solução\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nanilhas_reais = anilhados[.!occursin.(r\"^[A-Za-z]+$\", anilhados.ring), :]\npor_ave = combine(groupby(anilhas_reais, [:ring, :species]), nrow => :n)\nn_recapturadas = count(>(1), por_ave.n)\n```\n\n::: {#answer-7-3 .cell-output .cell-output-display execution_count=1}\n```\n4503\n```\n:::\n:::\n\n\n\n::: {#answer-7-3-check .cell execution_count=1}\n``` {.julia .cell-code}\nchecar(\"7.3\", n_recapturadas)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correto!\n```\n:::\n:::\n\n\n\nCerca de 4 500 aves contribuem com dois registros ou mais, uma delas com até 43. Tratar\nesses registros como independentes superestimaria o tamanho amostral — e os códigos de\ncor teriam acrescentado 27 \"indivíduos\" falsos à contagem.\n:::\n:::\n\n\n\n## Distribuições {#sec-eda-distribuicoes}\n\nA massa corporal de todas as aves cobre três ordens de grandeza, de beija-flores a\ngrandes aves marinhas. Em escala linear, quase tudo se acumula à esquerda; em escala\nlog, a forma aparece:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nmassas = collect(skipmissing(birds.mass_g))\n\nfig = Figure(size = (860, 340))\nax1 = Axis(fig[1, 1], xlabel = \"Massa corporal (g)\", ylabel = \"Registros\", title = \"(a) Linear\")\nhist!(ax1, massas, bins = 60, color = (:steelblue, 0.7))\nax2 = Axis(fig[1, 2], xlabel = \"Massa corporal (g, escala log)\", title = \"(b) Logarítmica\",\n           xscale = log10)\nhist!(ax2, massas, bins = 10 .^ range(0, 3.6, length = 60), color = (:steelblue, 0.7))\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Massa corporal de todas as aves pesadas, em escala linear (a) e logarítmica (b).](07-analise-exploratoria_files/figure-pdf/fig-escalas-massa-output-1.png){#fig-escalas-massa width=860 height=340 fig-pos='H'}\n:::\n:::\n\n\n\nTamanhos, áreas e concentrações são limitados em zero e crescem de forma\nmultiplicativa; por isso costumam ser assimétricos à direita e mais simétricos em\nescala log. É por isso que modelos dessas variáveis usam tão frequentemente o seu\nlogaritmo.\n\nDentro de uma espécie, o quadro é outro. Para o sabiá-coleira (*Turdus albicollis*),\numa das espécies mais registradas, compare a distribuição com uma curva normal de mesma\nmédia e desvio-padrão:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsabia = collect(skipmissing(birds.mass_g[birds.species .== \"Turdus albicollis\"]))\nμ, σ = mean(sabia), std(sabia)\n\nfig = Figure(size = (860, 340))\nax1 = Axis(fig[1, 1], xlabel = \"Massa corporal (g)\", ylabel = \"Densidade\",\n           title = \"(a) Histograma\")\nhist!(ax1, sabia, bins = 40, normalization = :pdf, color = (:seagreen, 0.6))\nxs = range(minimum(sabia), maximum(sabia), length = 200)\nlines!(ax1, xs, @.(exp(-(xs - μ)^2 / (2σ^2)) / (σ * sqrt(2π))), color = :black)\n\nax2 = Axis(fig[1, 2], xlabel = \"Quantis da normal\", ylabel = \"Massa corporal (g)\",\n           title = \"(b) QQ-plot\")\nn = length(sabia)\nz = quantile.(Normal(), ((1:n) .- 0.5) ./ n)\nscatter!(ax2, z, sort(sabia), color = (:seagreen, 0.5), markersize = 5)\nablines!(ax2, μ, σ, color = :black, linestyle = :dash)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Massa corporal de *Turdus albicollis*: histograma com uma curva normal de mesma média e desvio-padrão (a), e QQ-plot contra a normal (b).](07-analise-exploratoria_files/figure-pdf/fig-sabia-output-1.png){#fig-sabia width=860 height=340 fig-pos='H'}\n:::\n:::\n\n\n\nPerto da normal no meio, com algumas aves bem mais leves ou mais pesadas que as outras\n— visíveis como os pontos que se afastam da reta nas duas pontas do QQ-plot. Essas\ncaudas são o assunto da próxima seção.\n\n::: {.callout-note .exercise}\n## Sua vez 7.4 — Média ou mediana?\n\nCalcule a mediana e a média da massa corporal de *Turdus albicollis* e passe-as, nessa\nordem, como um vetor para `checar(\"7.4\", ...)`. Qual das duas é menos afetada pelas\naves extremas?\n\n::: {.callout-tip collapse=\"true\"}\n## Dica\n\n`sabia`, acima, já tem as massas. `[median(x), mean(x)]` monta o vetor.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solução\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncentro_sabia = [median(sabia), mean(sabia)]\n```\n\n::: {#answer-7-4 .cell-output .cell-output-display execution_count=1}\n```\n2-element Vector{Float64}:\n 66.0\n 66.74542818610924\n```\n:::\n:::\n\n\n\n::: {#answer-7-4-check .cell execution_count=1}\n``` {.julia .cell-code}\nchecar(\"7.4\", centro_sabia)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correto!\n```\n:::\n:::\n\n\n\n66 e 66,7 g: quase iguais, como se espera de uma distribuição aproximadamente\nsimétrica. A mediana ignora o quão extremas são as caudas; a média é puxada por elas.\nCom alguns registros de 26 g ou 114 g, a média se move pouco; com os erros grosseiros da\npróxima seção, se moveria muito mais.\n:::\n:::\n\n\n\n## Erros e outliers {#sec-eda-outliers}\n\nUm histograma geral não mostra o erro de uma ave de 14 g registrada com 1 240 g: 1 240 g\né uma massa perfeitamente comum para uma ave grande. Outliers em dados de atributos são\noutliers **em relação à espécie**. Um sinal simples e robusto compara cada massa com a\nmediana da sua espécie:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\npesadas = dropmissing(birds[:, [:species, :mass_g, :age, :status, :source]], :mass_g)\npesadas = transform(groupby(pesadas, :species),\n                    :mass_g => median => :species_median, nrow => :n_species)\npesadas.ratio = pesadas.mass_g ./ pesadas.species_median\n\nsuspeitas = sort(pesadas[(pesadas.n_species .>= 10) .& (pesadas.ratio .> 3), :],\n                 :ratio, rev = true)\nfirst(suspeitas[:, [:species, :mass_g, :species_median, :ratio, :age, :status]], 8)\n```\n\n::: {#mass-ratio .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|cccccc}\n\t& species & mass\\_g & species\\_median & ratio & age & status\\\\\n\t\\hline\n\t& String31 & Float64 & Float64 & Float64 & String15? & String7?\\\\\n\t\\hline\n\t1 & Thlypopsis sordida & 1240.0 & 14.0 & 88.5714 & Unknown & museum \\\\\n\t2 & Thlypopsis sordida & 1070.0 & 14.0 & 76.4286 & Unknown & museum \\\\\n\t3 & Corythopis delalandi & 214.0 & 15.0 & 14.2667 & Adult & live \\\\\n\t4 & Tityra cayana & 940.0 & 73.0 & 12.8767 & Juvenile & museum \\\\\n\t5 & Tityra cayana & 840.0 & 73.0 & 11.5068 & Juvenile & museum \\\\\n\t6 & Platyrinchus mystaceus & 102.0 & 9.0 & 11.3333 & \\emph{missing} & \\emph{missing} \\\\\n\t7 & Thalurania glaucopis & 50.0 & 4.5 & 11.1111 & Adult & live \\\\\n\t8 & Phaethornis eurynome & 55.0 & 5.0 & 11.0 & Adult & live \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\nO topo da lista mostra vários tipos de problema:\n\n- *Thlypopsis sordida*, uma saíra de 14 g, registrada com mais de 1 kg: quase certamente\n  um erro de digitação, talvez um separador decimal fora do lugar ou uma unidade errada.\n- Várias massas cerca de **dez vezes** a mediana da espécie — 102 g para um papa-moscas\n  de 9 g, 50 g para um beija-flor de 4,5 g: a assinatura de uma vírgula deslocada.\n- Jovens pesados de *Tityra cayana* em uma coleção de museu: talvez erros, talvez um\n  espécime com etiqueta trocada. Só a fonte pode dizer.\n\nAgora a outra cauda:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfirst(sort(pesadas[(pesadas.n_species .>= 10) .& (pesadas.ratio .< 1/3), :], :ratio)[:,\n      [:species, :mass_g, :species_median, :ratio, :age, :status]], 6)\n```\n\n::: {#mass-ratio-low .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|cccccc}\n\t& species & mass\\_g & species\\_median & ratio & age & status\\\\\n\t\\hline\n\t& String31 & Float64 & Float64 & Float64 & String15? & String7?\\\\\n\t\\hline\n\t1 & Crypturellus parvirostris & 8.5 & 185.0 & 0.0459459 & Unknown & museum \\\\\n\t2 & Aramides saracura & 22.5 & 346.0 & 0.0650289 & Unknown & museum \\\\\n\t3 & Aramides saracura & 22.5 & 346.0 & 0.0650289 & Juvenile & museum \\\\\n\t4 & Aramides saracura & 24.0 & 346.0 & 0.0693642 & Unknown & museum \\\\\n\t5 & Aramides saracura & 24.0 & 346.0 & 0.0693642 & Juvenile & museum \\\\\n\t6 & Asio clamator & 34.5 & 470.0 & 0.0734043 & Unknown & museum \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\nAqui alguns dos \"outliers\" são reais. Uma saracura-do-mato (*Aramides saracura*,\nmediana de 346 g) de 24 g marcada como jovem é plausivelmente um filhote. Apagá-la\nremoveria uma ave real; mantê-la em uma análise de tamanho adulto a distorceria.\n\n::: {.callout-important}\n## Sinalize, não apague\n\nUma regra estatística só pode dizer que um valor é incomum, nunca que ele está errado.\nSinalize os valores suspeitos, olhe-os um a um, volte à fonte quando puder e decida — e\nregistre o que decidiu e por quê, em código, para que a decisão possa ser revisada. Em\nmuitas análises, a escolha certa é restringir os dados ao que a pergunta trata (adultos,\ndigamos) em vez de remover pontos individuais.\n:::\n\nOs dados também carregam um problema mais discreto, a **precisão**. A maioria das\nmassas é um número inteiro:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nmean(pesadas.mass_g .== round.(pesadas.mass_g))\n```\n\n::: {#precision .cell-output .cell-output-display execution_count=1}\n```\n0.7217974646080995\n```\n:::\n:::\n\n\n\n72% das massas são inteiras, o que quer dizer que muitas foram pesadas com precisão de\n1 grama. Para um beija-flor de 3 g, arredondar ao grama é um erro de até 17%; para um\nsabiá, menos de 1%. Uma precisão que varia com o tamanho do animal é fácil de não notar,\ne vale saber disso antes de comparar espécies pequenas.\n\n::: {.callout-note .exercise}\n## Sua vez 7.5 — Quantas massas suspeitas?\n\nConte os registros cuja massa é mais de 3 vezes, ou menos de um terço, da mediana da\nsua espécie, entre as espécies com pelo menos 10 registros pesados. Passe o número para\n`checar(\"7.5\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Dica\n\n`pesadas` já tem `ratio` e `n_species`. Combine as condições com `.&` e `.|` e conte os\n`true` com `count`.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solução\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nn_suspeitas = count((pesadas.n_species .>= 10) .&\n                    ((pesadas.ratio .> 3) .| (pesadas.ratio .< 1/3)))\n```\n\n::: {#answer-7-5 .cell-output .cell-output-display execution_count=1}\n```\n291\n```\n:::\n:::\n\n\n\n::: {#answer-7-5-check .cell execution_count=1}\n``` {.julia .cell-code}\nchecar(\"7.5\", n_suspeitas)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correto!\n```\n:::\n:::\n\n\n\n291 de cerca de 60 000 registros pesados, 0,5%: poucos, mas suficientes para arruinar a\nmédia de uma espécie. O limiar de 3 é uma escolha, não uma regra; com 2, você\nsinalizaria mais que o dobro.\n:::\n:::\n\n\n\n## Relações e colinearidade {#sec-eda-colinearidade}\n\nAtributos morfológicos andam juntos: aves grandes têm asas longas, caudas longas, pernas\nlongas e bicos longos. Para ver com que força, resuma cada espécie pela mediana de cada\natributo — a mediana, por causa dos outliers acima — e compare as espécies:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\natributos = [:mass_g, :wing_mm, :tail_mm, :tarsus_mm, :bill_mm]\nmediana_ou_missing(x) = (v = collect(skipmissing(x)); isempty(v) ? missing : median(v))\n\npor_especie_med = dropmissing(combine(groupby(birds, :species),\n                                      [t => mediana_ou_missing => t for t in atributos]...))\nlog_atributos = DataFrame(log.(Matrix(por_especie_med[:, atributos])), atributos)\n\nnrow(por_especie_med)\n```\n\n::: {#species-traits .cell-output .cell-output-display execution_count=1}\n```\n538\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nround.(cor(Matrix(log_atributos)); digits = 2)\n```\n\n::: {#correlation-matrix .cell-output .cell-output-display execution_count=1}\n```\n5×5 Matrix{Float64}:\n 1.0   0.93  0.71  0.81  0.72\n 0.93  1.0   0.77  0.72  0.64\n 0.71  0.77  1.0   0.56  0.5\n 0.81  0.72  0.56  1.0   0.64\n 0.72  0.64  0.5   0.64  1.0\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nrotulos = [\"log massa\", \"log asa\", \"log cauda\", \"log tarso\", \"log bico\"]\nfig = Figure(size = (820, 820))\nfor i in 1:5, j in 1:5\n    ax = Axis(fig[i, j], xlabel = i == 5 ? rotulos[j] : \"\", ylabel = j == 1 ? rotulos[i] : \"\",\n              xticklabelsvisible = i == 5, yticklabelsvisible = j == 1 && i != 1)\n    if i == j                  # diagonal: a distribuição de cada atributo (contagens)\n        hist!(ax, log_atributos[:, i], bins = 25, color = (:grey60, 0.8))\n    else\n        scatter!(ax, log_atributos[:, j], log_atributos[:, i], markersize = 3,\n                 color = (:steelblue, 0.5))\n    end\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Medianas de cinco atributos por espécie, em escala log, um ponto por espécie. Fora da diagonal, cada painel mostra um par de atributos; na diagonal, a distribuição de cada atributo.](07-analise-exploratoria_files/figure-pdf/fig-pares-output-1.png){#fig-pares width=820 height=820 fig-pos='H'}\n:::\n:::\n\n\n\nMassa e comprimento da asa são quase uma única variável entre espécies. Se os dois\nentrassem em um modelo como preditores, o modelo não conseguiria separar os seus\nefeitos: as estimativas seriam instáveis e os erros-padrão, grandes. O **fator de\ninflação da variância** (VIF) mede isso. Para cada preditor, faça a regressão dele em\ntodos os outros; com o $R^2$ dessa regressão, $\\text{VIF} = 1 / (1 - R^2)$:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfunction vif(df, col)\n    outros = setdiff(propertynames(df), [col])\n    f = Term(col) ~ sum(Term.(outros))\n    return 1 / (1 - r2(lm(f, df)))\nend\n\nDataFrame(atributo = atributos,\n          vif = round.([vif(log_atributos, t) for t in atributos]; digits = 1))\n```\n\n::: {#vif .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|cc}\n\t& atributo & vif\\\\\n\t\\hline\n\t& Symbol & Float64\\\\\n\t\\hline\n\t1 & mass\\_g & 11.9 \\\\\n\t2 & wing\\_mm & 9.7 \\\\\n\t3 & tail\\_mm & 2.5 \\\\\n\t4 & tarsus\\_mm & 3.0 \\\\\n\t5 & bill\\_mm & 2.1 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\n@zuur2010protocol usam um limite de 3; outros autores usam 5 ou 10. Massa e asa ficam\nacima de todos eles. As respostas usuais são manter só um de cada grupo colinear,\ncombiná-los (um índice de tamanho) ou fazer uma pergunta que não precise deles\nseparadamente.\n\n::: {.callout-note .exercise}\n## Sua vez 7.6 — Massa e asa\n\nQual é a correlação entre log da massa corporal e log do comprimento da asa entre\nespécies, usando as medianas por espécie acima? Passe-a para `checar(\"7.6\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Dica\n\n`cor(x, y)` em duas colunas de `log_atributos`.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solução\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nr_massa_asa = cor(log_atributos.mass_g, log_atributos.wing_mm)\n```\n\n::: {#answer-7-6 .cell-output .cell-output-display execution_count=1}\n```\n0.9326447165263585\n```\n:::\n:::\n\n\n\n::: {#answer-7-6-check .cell execution_count=1}\n``` {.julia .cell-code}\nchecar(\"7.6\", r_massa_asa)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correto!\n```\n:::\n:::\n\n\n\nCerca de 0,93. Entre espécies, esses dois atributos carregam quase a mesma informação.\nDentro de uma espécie, a correlação é muito mais fraca — cerca de 0,25 entre\nindivíduos de *Turdus albicollis* —, porque indivíduos de uma espécie variam pouco em\ntamanho: a colinearidade depende da escala da pergunta.\n:::\n:::\n\n\n\n## Por que os gráficos: o quarteto de Anscombe {#sec-anscombe}\n\nResumos não substituem olhar. @anscombe1973graphs construiu quatro pequenos conjuntos de\ndados com as mesmas médias, variâncias, correlações e retas de regressão:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nanscombe = dataset(\"datasets\", \"anscombe\")\nDataFrame(conjunto = 1:4,\n          media_x = [mean(anscombe[:, \"X$i\"]) for i in 1:4],\n          media_y = [round(mean(anscombe[:, \"Y$i\"]); digits = 2) for i in 1:4],\n          cor_xy = [round(cor(anscombe[:, \"X$i\"], anscombe[:, \"Y$i\"]); digits = 3) for i in 1:4])\n```\n\n::: {#anscombe-stats .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|cccc}\n\t& conjunto & media\\_x & media\\_y & cor\\_xy\\\\\n\t\\hline\n\t& Int64 & Float64 & Float64 & Float64\\\\\n\t\\hline\n\t1 & 1 & 9.0 & 7.5 & 0.816 \\\\\n\t2 & 2 & 9.0 & 7.5 & 0.816 \\\\\n\t3 & 3 & 9.0 & 7.5 & 0.816 \\\\\n\t4 & 4 & 9.0 & 7.5 & 0.817 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (760, 560))\nfor i in 1:4\n    x, y = anscombe[:, \"X$i\"], anscombe[:, \"Y$i\"]\n    ax = Axis(fig[(i - 1) ÷ 2 + 1, (i - 1) % 2 + 1], title = \"Conjunto $i\",\n              limits = (3, 20, 3, 14))\n    scatter!(ax, x, y, color = :steelblue)\n    b = coef(lm(@formula(y ~ x), DataFrame(; x, y)))\n    ablines!(ax, b[1], b[2], color = :darkorange)\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![O quarteto de Anscombe: quatro conjuntos de dados com as mesmas estatísticas resumo e a mesma reta de mínimos quadrados.](07-analise-exploratoria_files/figure-pdf/fig-anscombe-output-1.png){#fig-anscombe width=760 height=560 fig-pos='H'}\n:::\n:::\n\n\n\nO primeiro parece o que um modelo linear supõe. O segundo é uma curva. No terceiro, um\nponto afasta a reta de uma relação de resto perfeita. No quarto, toda a inclinação\ndepende de uma única observação. Só os gráficos mostram isso.\n\n## Desafios {.unnumbered}\n\n1. Faça o gráfico das coordenadas de todos os registros (`lon`, `lat`) e pinte-os por\n   `outside_range`. Os registros marcados como fora da distribuição da espécie estão\n   onde você esperaria? Há pontos fora da região da Mata Atlântica?\n2. Machos e fêmeas de *Chiroxiphia caudata* (tangará) diferem muito na plumagem. Diferem\n   na massa? Compare as distribuições, não só as medianas, e decida o que fazer com os\n   registros de sexo `\"Unknown\"`.\n3. Repita a regra de outliers da @sec-eda-outliers para o comprimento da asa. As\n   espécies com asas suspeitas são as mesmas com massas suspeitas? O que isso diria\n   sobre a origem dos erros?\n\n",
    "supporting": [
      "07-analise-exploratoria_files/figure-pdf"
    ],
    "filters": []
  }
}