{
  "hash": "dc75d2e634ad0f7662b1b77cddf03572",
  "result": {
    "engine": "julia",
    "markdown": "# Linear models {#sec-linear-models}\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nusing TidierData\nusing DataFrames, CSV\nusing GLM, StatsModels, StatsBase, Statistics, Distributions\nusing HypothesisTests\nusing CairoMakie\nusing MixedModels\n\nCairoMakie.activate!(type = \"png\")\n\nponds = @chain CSV.read(joinpath(\"..\", \"data\", \"ponds.csv\"), DataFrame) begin\n    @drop_missing(canopy)\n    @mutate(log_area = log(area_m2))\nend\n\nnrow(ponds)\n```\n\n::: {#setup-07 .cell-output .cell-output-display execution_count=1}\n```\n173\n```\n:::\n:::\n\n\n\n\n\n::: {.callout-note .exercise}\n## Exercises in this chapter\n\nIn the *Your turn* boxes you fit a model and pass a number extracted from it — a\np-value, coefficients, an interval — to `check`. All of them use the ponds with canopy\nrecorded, as in this chapter. Start each session with:\n\n```julia\ninclude(\"exercises/check.jl\")\nusing TidierData, DataFrames, CSV, GLM, StatsModels, Statistics\nusing HypothesisTests, MixedModels\nponds = @chain CSV.read(joinpath(\"data\", \"ponds.csv\"), DataFrame) begin\n    @drop_missing(canopy)\n    @mutate(log_area = log(area_m2))\nend\n```\n:::\n\n## Hypothesis tests {#sec-tests}\n\nBefore models, the basics. `HypothesisTests.jl` covers the usual repertoire.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nperm = @chain ponds begin @filter(hydro == \"permanent\") end\ntemp_ = @chain ponds begin @filter(hydro == \"temporary\") end\n\nUnequalVarianceTTest(perm.richness, temp_.richness)\n```\n\n::: {#ttest .cell-output .cell-output-display execution_count=1}\n```\nTwo sample t-test (unequal variance)\n------------------------------------\nPopulation details:\n    parameter of interest:   Mean difference\n    value under h_0:         0\n    point estimate:          1.01849\n    95% confidence interval: (-0.452, 2.489)\n\nTest summary:\n    outcome with 95% confidence: fail to reject h_0\n    two-sided p-value:           0.1734\n\nDetails:\n    number of observations:   [95,78]\n    t-statistic:              1.3673234271337709\n    degrees of freedom:       168.0376473521344\n    empirical standard error: 0.7448775533304762\n```\n:::\n:::\n\n\n\n::: {.r-equivalent}\n**In R**\n\n`t.test(richness ~ hydro, data = ponds)` uses Welch by default — the same as\n`UnequalVarianceTTest`. For the equal-variance test, use `EqualVarianceTTest`.\n:::\n\n::: {.callout-note .exercise}\n## Your turn 8.1 — Does hydroperiod affect body size?\n\nCompare `body_size` between permanent and temporary ponds with a Welch t test. Pass\nits p-value to `check(\"8.1\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\nReuse `perm` and `temp_` from the block above. `pvalue(test)` extracts the p-value.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nt_body = UnequalVarianceTTest(perm.body_size, temp_.body_size)\npvalue(t_body)\n```\n\n::: {#answer-8-1 .cell-output .cell-output-display execution_count=1}\n```\n0.10269215805061378\n```\n:::\n:::\n\n\n\n::: {#answer-8-1-check .cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"8.1\", pvalue(t_body))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n:::\n\n\n\np ≈ 0.10: no evidence of a difference. Here we can go further than usual, because in\nthe simulation hydroperiod really has no effect on body size. With real data, a\nnon-significant test does not show that there is no effect — only that the data\ncannot tell.\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n# normality and correlation\n(\n    ks_normal = ExactOneSampleKSTest(\n        (ponds.body_size .- mean(ponds.body_size)) ./ std(ponds.body_size),\n        Normal(0, 1)) |> pvalue,\n    correlation = CorrelationTest(ponds.canopy, ponds.body_size) |> pvalue,\n)\n```\n\n::: {#other-tests .cell-output .cell-output-display execution_count=1}\n```\n(ks_normal = 0.9802464726099859, correlation = 4.331805547836102e-5)\n```\n:::\n:::\n\n\n\n## Simple linear regression {#sec-simple-lm}\n\nThe dataset's continuous response is `body_size`, mean body size.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nm1 = lm(@formula(body_size ~ temp_c), ponds)\n```\n\n::: {#simple-lm .cell-output .cell-output-display execution_count=1}\n```\nStatsModels.TableRegressionModel{LinearModel{GLM.LmResp{Vector{Float64}}, GLM.DensePredChol{Float64, LinearAlgebra.CholeskyPivoted{Float64, Matrix{Float64}, Vector{Int64}}}}, Matrix{Float64}}\n\nbody_size ~ 1 + temp_c\n\nCoefficients:\n─────────────────────────────────────────────────────────────────────────\n                 Coef.  Std. Error      t  Pr(>|t|)  Lower 95%  Upper 95%\n─────────────────────────────────────────────────────────────────────────\n(Intercept)  13.1837     1.5861      8.31    <1e-13  10.0528     16.3145\ntemp_c        0.921736   0.0645072  14.29    <1e-30   0.794403    1.04907\n─────────────────────────────────────────────────────────────────────────\n```\n:::\n:::\n\n\n\nThe formula interface of `StatsModels.jl` matches R's: `~`, `+`, `*`, `:`, `-1` and\ninline transformations such as `log(x)` all work as expected.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n(\n    r2       = r2(m1),\n    adj_r2   = adjr2(m1),\n    aic      = aic(m1),\n    coefs    = coef(m1),\n    intervals = confint(m1),\n)\n```\n\n::: {#lm-extractors .cell-output .cell-output-display execution_count=1}\n```\n(r2 = 0.544209635943369, adj_r2 = 0.5415441952178917, aic = 801.3969591368274, coefs = [13.1836826870694, 0.9217361109462926], intervals = [10.05281805410378 16.314547320035018; 0.7944032137607457 1.0490690081318395])\n```\n:::\n:::\n\n\n\n::: {.callout-note .exercise}\n## Your turn 8.2 — Body size and canopy\n\nFit a simple regression of `body_size` on `canopy` and pass both coefficients to\n`check(\"8.2\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\n`coef(m)` returns the intercept and the slope, in that order.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nm_canopy = lm(@formula(body_size ~ canopy), ponds)\ncoef(m_canopy)\n```\n\n::: {#answer-8-2 .cell-output .cell-output-display execution_count=1}\n```\n2-element Vector{Float64}:\n 38.134435320100664\n -0.049665628867203285\n```\n:::\n:::\n\n\n\n::: {#answer-8-2-check .cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"8.2\", coef(m_canopy))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n:::\n\n\n\nThe slope, about −0.050, is further from the true −0.04 than in `m2` (next section),\nbecause this model leaves temperature out.\n:::\n:::\n\n\n\n## Multiple regression {#sec-multiple-lm}\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nm2 = lm(@formula(body_size ~ temp_c + canopy), ponds)\n```\n\n::: {#multiple-lm .cell-output .cell-output-display execution_count=1}\n```\nStatsModels.TableRegressionModel{LinearModel{GLM.LmResp{Vector{Float64}}, GLM.DensePredChol{Float64, LinearAlgebra.CholeskyPivoted{Float64, Matrix{Float64}, Vector{Int64}}}}, Matrix{Float64}}\n\nbody_size ~ 1 + temp_c + canopy\n\nCoefficients:\n───────────────────────────────────────────────────────────────────────────\n                  Coef.  Std. Error      t  Pr(>|t|)  Lower 95%   Upper 95%\n───────────────────────────────────────────────────────────────────────────\n(Intercept)  15.761      1.54229     10.22    <1e-18  12.7164    18.8055\ntemp_c        0.901451   0.059815    15.07    <1e-32   0.783375   1.01953\ncanopy       -0.0423641  0.00777948  -5.45    <1e-06  -0.057721  -0.0270073\n───────────────────────────────────────────────────────────────────────────\n```\n:::\n:::\n\n\n\nThe generating process (see `scripts/make_data.jl`) used\n$38.0 + 0.9\\,(\\text{temp} - 24.5) - 0.04\\,\\text{canopy}$. Compare with the estimates:\nthis is the payoff of teaching with simulated data.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nDataFrame(\n    term      = coefnames(m2),\n    estimated = round.(coef(m2), digits = 3),\n    truth     = [38.0 - 0.9 * 24.5, 0.9, -0.04],\n)\n```\n\n::: {#truth-comparison .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|ccc}\n\t& term & estimated & truth\\\\\n\t\\hline\n\t& String & Float64 & Float64\\\\\n\t\\hline\n\t1 & (Intercept) & 15.761 & 15.95 \\\\\n\t2 & temp\\_c & 0.901 & 0.9 \\\\\n\t3 & canopy & -0.042 & -0.04 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\n::: {.callout-note .exercise}\n## Your turn 8.3 — Does the interval catch the truth?\n\nFit `body_size ~ temp_c + canopy + hydro` and compute the 95% confidence interval for\nthe `temp_c` coefficient. Does it contain the true value, 0.9? Pass the interval (two\nnumbers) to `check(\"8.3\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\n`confint(m)` returns one row per coefficient; `temp_c` is the second row, so\n`confint(m)[2, :]`.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nm_hydro = lm(@formula(body_size ~ temp_c + canopy + hydro), ponds)\nci_temp = confint(m_hydro)[2, :]\n```\n\n::: {#answer-8-3 .cell-output .cell-output-display execution_count=1}\n```\n2-element Vector{Float64}:\n 0.7785892869884922\n 1.0167713699307883\n```\n:::\n:::\n\n\n\n::: {#answer-8-3-check .cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"8.3\", ci_temp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n:::\n\n\n\nThe interval, about [0.78, 1.02], contains 0.9. It would not in about one of every 20\nsimulated datasets: that is what \"95%\" means.\n:::\n:::\n\n\n\n## Categorical predictors and interactions {#sec-categorical}\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nm3 = lm(@formula(body_size ~ temp_c + canopy + region), ponds)\n```\n\n::: {#categorical-lm .cell-output .cell-output-display execution_count=1}\n```\nStatsModels.TableRegressionModel{LinearModel{GLM.LmResp{Vector{Float64}}, GLM.DensePredChol{Float64, LinearAlgebra.CholeskyPivoted{Float64, Matrix{Float64}, Vector{Int64}}}}, Matrix{Float64}}\n\nbody_size ~ 1 + temp_c + canopy + region\n\nCoefficients:\n────────────────────────────────────────────────────────────────────────────────\n                       Coef.  Std. Error      t  Pr(>|t|)  Lower 95%   Upper 95%\n────────────────────────────────────────────────────────────────────────────────\n(Intercept)       15.769      1.54634     10.20    <1e-18  12.7162    18.8218\ntemp_c             0.893539   0.0597492   14.95    <1e-31   0.775583   1.0115\ncanopy            -0.0437397  0.00780336  -5.61    <1e-07  -0.059145  -0.0283344\nregion: Atlantic   0.664579   0.436092     1.52    0.1294  -0.196347   1.52551\nregion: Cerrado    0.018937   0.43474      0.04    0.9653  -0.83932    0.877194\n────────────────────────────────────────────────────────────────────────────────\n```\n:::\n:::\n\n\n\nJulia treats `String` and `CategoricalArray` columns as factors automatically, with\ntreatment (dummy) coding and the first level as reference — same as R. To change the\nreference level or the contrast scheme:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nm3b = lm(@formula(body_size ~ temp_c + region), ponds;\n         contrasts = Dict(:region => DummyCoding(base = \"Cerrado\")))\n\ncoefnames(m3b)\n```\n\n::: {#contrasts .cell-output .cell-output-display execution_count=1}\n```\n4-element Vector{String}:\n \"(Intercept)\"\n \"temp_c\"\n \"region: Amazon\"\n \"region: Atlantic\"\n```\n:::\n:::\n\n\n\n::: {.callout-note .exercise}\n## Your turn 8.4 — Choosing the reference\n\nFit `body_size ~ temp_c + region` with the Atlantic region as the reference level and\npass the coefficient names to `check(\"8.4\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\nCopy the `contrasts` argument from the block above and change the level.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nm_atl = lm(@formula(body_size ~ temp_c + region), ponds;\n           contrasts = Dict(:region => DummyCoding(base = \"Atlantic\")))\ncoefnames(m_atl)\n```\n\n::: {#answer-8-4 .cell-output .cell-output-display execution_count=1}\n```\n4-element Vector{String}:\n \"(Intercept)\"\n \"temp_c\"\n \"region: Amazon\"\n \"region: Cerrado\"\n```\n:::\n:::\n\n\n\n::: {#answer-8-4-check .cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"8.4\", coefnames(m_atl))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n:::\n\n\n\nThe reference level has no coefficient of its own: it is absorbed by the intercept,\nand the other regions are compared with it. Without `contrasts`, the reference is the\nfirst level in alphabetical order, Amazon.\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nm4 = lm(@formula(body_size ~ temp_c * hydro), ponds)\n```\n\n::: {#interaction-lm .cell-output .cell-output-display execution_count=1}\n```\nStatsModels.TableRegressionModel{LinearModel{GLM.LmResp{Vector{Float64}}, GLM.DensePredChol{Float64, LinearAlgebra.CholeskyPivoted{Float64, Matrix{Float64}, Vector{Int64}}}}, Matrix{Float64}}\n\nbody_size ~ 1 + temp_c + hydro + temp_c & hydro\n\nCoefficients:\n───────────────────────────────────────────────────────────────────────────────────────\n                               Coef.  Std. Error      t  Pr(>|t|)  Lower 95%  Upper 95%\n───────────────────────────────────────────────────────────────────────────────────────\n(Intercept)                14.8606     2.16225     6.87    <1e-09  10.5921    19.1291\ntemp_c                      0.847037   0.0890498   9.51    <1e-16   0.671244   1.02283\nhydro: temporary           -3.33192    3.20923    -1.04    0.3006  -9.66726    3.00341\ntemp_c & hydro: temporary   0.147595   0.130228    1.13    0.2587  -0.109489   0.404679\n───────────────────────────────────────────────────────────────────────────────────────\n```\n:::\n:::\n\n\n\n## Model selection and comparison {#sec-selection}\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nmodels = [\"temp\"          => m1,\n          \"temp+canopy\"   => m2,\n          \"temp+can+reg\"  => m3,\n          \"temp*hydro\"    => m4]\n\nDataFrame(\n    model  = first.(models),\n    k      = [length(coef(m)) for (_, m) in models],\n    aic    = round.([aic(m) for (_, m) in models], digits = 1),\n    bic    = round.([bic(m) for (_, m) in models], digits = 1),\n    adj_r2 = round.([adjr2(m) for (_, m) in models], digits = 3),\n)\n```\n\n::: {#model-comparison .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|ccccc}\n\t& model & k & aic & bic & adj\\_r2\\\\\n\t\\hline\n\t& String & Int64 & Float64 & Float64 & Float64\\\\\n\t\\hline\n\t1 & temp & 2 & 801.4 & 810.9 & 0.542 \\\\\n\t2 & temp+canopy & 3 & 775.6 & 788.2 & 0.607 \\\\\n\t3 & temp+can+reg & 5 & 776.1 & 795.0 & 0.611 \\\\\n\t4 & temp*hydro & 4 & 803.5 & 819.3 & 0.541 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n# F test between nested models, equivalent to anova() in R\nftest(m1.model, m2.model, m3.model)\n```\n\n::: {#ftest .cell-output .cell-output-display execution_count=1}\n```\nF-test: 3 models fitted on 173 observations\n─────────────────────────────────────────────────────────────────────\n     DOF  ΔDOF        SSR       ΔSSR      R²     ΔR²       F*   p(>F)\n─────────────────────────────────────────────────────────────────────\n[1]    3        1005.3438             0.5442                         \n[2]    4     1   856.0194  -149.3243  0.6119  0.0677  29.6549  <1e-06\n[3]    6     2   839.0138   -17.0056  0.6196  0.0077   1.7026  0.1853\n─────────────────────────────────────────────────────────────────────\n```\n:::\n:::\n\n\n\n## Diagnostics {#sec-diagnostics}\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nres = residuals(m3)\nfit_ = predict(m3)\n\nfig = Figure(size = (860, 350))\n\nax1 = Axis(fig[1, 1], xlabel = \"Fitted values\", ylabel = \"Residuals\",\n           title = \"(a) Residuals vs fitted\")\nscatter!(ax1, fit_, res, color = (:steelblue, 0.6))\nhlines!(ax1, 0, color = :grey40, linestyle = :dash)\n\nax2 = Axis(fig[1, 2], xlabel = \"Theoretical quantiles\", ylabel = \"Sample quantiles\",\n           title = \"(b) QQ plot\")\n# NOTE: Makie exports `qqnorm` as a plot recipe, so the quantiles are\n# computed explicitly here rather than taken from a helper.\nn = length(res)\ntheoretical = quantile.(Normal(0, 1), ((1:n) .- 0.5) ./ n)\nscatter!(ax2, theoretical, sort(res), color = (:darkorange, 0.6))\nablines!(ax2, 0, std(res), color = :grey40, linestyle = :dash)\n\nax3 = Axis(fig[1, 3], xlabel = \"Residuals\", ylabel = \"Frequency\",\n           title = \"(c) Distribution\")\nhist!(ax3, res, bins = 20, color = (:seagreen, 0.7))\n\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Residual diagnostics for model `m3`.](08-linear-models_files/figure-pdf/fig-diagnostics-output-1.png){#fig-diagnostics width=860 height=350 fig-pos='H'}\n:::\n:::\n\n\n\n::: {.callout-warning}\n## A real gap\n\nR has `plot(model)`, which returns the four diagnostic plots at once, and\n`performance::check_model()`, which goes much further. Julia has no consolidated\nequivalent; the diagnostics above are assembled by hand. This is a genuine gap, and\nexactly the kind of thing a community package would fix well.\n:::\n\n::: {.callout-note .exercise}\n## Your turn 8.5 — How many large residuals?\n\nIf the residuals of `m3` are roughly normal, about 5% of them should lie more than two\nstandard deviations from zero. Compute the proportion that does and pass it to\n`check(\"8.5\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\nDivide `res` (from the diagnostics block) by `std(res)`, then take the mean of\n`abs.(z) .> 2` — the mean of `true`/`false` values is a proportion.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nz = res ./ std(res)\nprop_large = mean(abs.(z) .> 2)\n```\n\n::: {#answer-8-5 .cell-output .cell-output-display execution_count=1}\n```\n0.057803468208092484\n```\n:::\n:::\n\n\n\n::: {#answer-8-5-check .cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"8.5\", prop_large)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n:::\n\n\n\nAbout 5.8% — 10 of 173 residuals, close to the 5% expected. This is a numerical\ncounterpart to the QQ plot above.\n:::\n:::\n\n\n\n## Mixed models {#sec-mixed-models}\n\n`MixedModels.jl` [@mixedmodelsjl] is maintained by Douglas Bates, first author of\n`lme4` [@bates2015lme4], and uses the same formula notation — including `(1 | group)`.\n\nOn performance: comparisons between the two depend heavily on the model, the size of\nthe data and the random-effects structure, and I know of no published benchmark I can\ncite here. If fitting time matters for your problem, measure it on your own case.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nmm1 = fit(MixedModel,\n          @formula(body_size ~ temp_c + canopy + (1 | region)),\n          ponds)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\rMinimizing 2    Time: 0:00:00 (72.62 ms/it)\r\n   objective: 780.4261079240766\r\n\r\rMinimizing 18    Time: 0:00:00 (15.95 ms/it)\n```\n:::\n\n::: {#lmm .cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|             |    Est. |     SE |     z |      p | σ_region |\n|:----------- | -------:| ------:| -----:| ------:| --------:|\n| (Intercept) | 15.7973 | 1.5290 | 10.33 | <1e-24 |   0.1246 |\n| temp_c      |  0.9002 | 0.0592 | 15.20 | <1e-51 |          |\n| canopy      | -0.0426 | 0.0077 | -5.52 | <1e-07 |          |\n| Residual    |  2.2209 |        |       |        |          |\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n(\n    fixed_effects = fixef(mm1),\n    variance      = VarCorr(mm1),\n    icc           = first(mm1.σs.region)^2 /\n                    (first(mm1.σs.region)^2 + mm1.σ^2),\n)\n```\n\n::: {#lmm-components .cell-output .cell-output-display execution_count=1}\n```\n(fixed_effects = [15.79726348938969, 0.9002362213830247, -0.042569241640192566], variance = Variance components:\n            Column   Variance Std.Dev. \nregion   (Intercept)  0.015537 0.124649\nResidual              4.932481 2.220919\n, icc = 0.003140144265734588)\n```\n:::\n:::\n\n\n\n::: {.r-equivalent}\n**In R**\n\n```r\nlmer(body_size ~ temp_c + canopy + (1 | region), data = ponds)\n```\n\nIdentical, down to the `(1 | group)` notation. `MixedModels.jl` also supports\n`(1 + x | group)`, `(1 | a) + (1 | b)` and nested terms.\n:::\n\n::: {.callout-note .exercise}\n## Your turn 8.6 — A random intercept for region\n\nFit a mixed model of `body_size` on `temp_c` with a random intercept for `region` and\npass its fixed effects to `check(\"8.6\", ...)`. Then look at `VarCorr` of your model:\nhow much variation does region account for?\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\nSame structure as `mm1`, with a shorter formula. `fixef(mm)` returns the fixed\neffects.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nmm_temp = fit(MixedModel, @formula(body_size ~ temp_c + (1 | region)), ponds;\n              progress = false)\nfixef(mm_temp)\n```\n\n::: {#answer-8-6 .cell-output .cell-output-display execution_count=1}\n```\n2-element Vector{Float64}:\n 13.183682687070245\n  0.9217361109462586\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"8.6\", fixef(mm_temp))\nVarCorr(mm_temp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n\n::: {#answer-8-6-check .cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|          | Column      |  Variance | Std.Dev |\n|:-------- |:----------- | ---------:| -------:|\n| region   | (Intercept) |   0.00000 | 0.00000 |\n| Residual |             |   5.81124 | 2.41065 |\n\n:::\n:::\n\n\n\nThe region variance is estimated as exactly zero — a *singular* fit. The simulation\nhas no region effect on body size, and three regions give very little information\nabout a variance anyway. With a zero variance, the mixed model reduces to\n`lm(@formula(body_size ~ temp_c), ponds)`: compare the coefficients.\n:::\n:::\n\n\n\n::: {#lmm-bootstrap .cell execution_count=0}\n``` {.julia .cell-code}\n# parametric bootstrap intervals — fast enough to be routine\nusing Random\nboot = parametricbootstrap(MersenneTwister(42), 1000, mm1)\nDataFrame(shortestcovint(boot))\n```\n:::\n\n\n\n## Challenges {.unnumbered}\n\n1. Fit `body_size ~ canopy` separately for each region and compare the slopes with those\n   of a single model with a `canopy * region` interaction. Why do they agree?\n2. Does `m4` have a significant interaction? The simulation has no `temp_c × hydro`\n   interaction: if yours were significant, what would that mean?\n3. In 8.6 the region variance came out as zero. Compare `mm1` with a model that treats\n   `region` as a fixed effect. With three regions, which would you report, and why?\n\n",
    "supporting": [
      "08-linear-models_files/figure-pdf"
    ],
    "filters": []
  }
}