project:
  type: book
  output-dir: _book

metadata-files:
  - ../_shared/common.yml

lang: pt

book:
  title: "Análises Ecológicas em Julia"
  subtitle: "Uma introdução à ciência de dados ecológicos com Julia"
  author:
    - name: "Eduardo Santos"
      affiliation: "University of Alberta"
      email: "esantos2@ualberta.ca"
  date: today
  date-format: "DD/MM/YYYY"
  language: pt
  search:
    location: sidebar
  sidebar:
    style: docked
  chapters:
    - index.qmd
    - part: "Fundamentos"
      chapters:
        - 01-introducao.qmd
        - 02-perguntas.qmd
        - 03-pre-requisitos.qmd
        - 04-introducao-julia.qmd
    - part: "Manipulação e exploração de dados"
      chapters:
        - 05-tidier.qmd
        - 06-visualizacao.qmd
        - 07-analise-exploratoria.qmd
    - part: "Modelagem"
      chapters:
        - 08-modelos-lineares.qmd
        - 09-glm.qmd
    - part: "Programação para ecologia"
      chapters:
        - 10-funcoes.qmd
        - 11-reamostragem.qmd
    - 99-referencias.qmd
