{
  "hash": "38828f55fe7ea6bd98b1a2c516883886",
  "result": {
    "engine": "julia",
    "markdown": "# Exploratory data analysis {#sec-exploratory}\n\nBefore any model, look at the data. Exploration has four jobs [@zuur2010protocol]: find\n**errors and outliers**, understand the **structure** of the data — what counts as a\nreplicate —, see the **distributions** that models will have to describe, and detect\n**collinearity** between variables that a model will struggle to separate. Skipping it\ndoes not save time: the problems are still there, and they surface later as strange\nmodel results.\n\nThe simulated ponds of the previous chapters are too clean for this. This chapter uses\nreal data, with all the problems real data have.\n\n::: {.callout-note}\n## Where this chapter comes from\n\nLike @sec-own-functions and @sec-resampling, this chapter is **inspired by** **ecoR**\n[@oliveira_ecor], the R course wiki of the Instituto de Biociências, Universidade de\nSão Paulo, produced and maintained by Alexandre Adalardo de Oliveira. Its sequence —\nchecking the data frame, descriptive statistics, univariate graphs, relationships\nbetween variables, and the Anscombe quartet — follows ecoR's exploratory-analysis\nmodule. The text, data, examples and exercises here are written from scratch for Julia;\nthe authors of ecoR have not reviewed this book.\n\nIf you read Portuguese and want to go further, the original material is freely\navailable (CC BY-SA 4.0):\n\n- [4. Análise Exploratória de Dados](https://ecor.ib.usp.br/doku.php?id=03_apostila:05-exploratoria)\n  — the course notes;\n- [4. Tutoriais de Análise Exploratória de Dados](https://ecor.ib.usp.br/doku.php?id=02_tutoriais:tutorial4:start)\n  — the step-by-step tutorial;\n- [exercises on exploratory analysis](https://ecor.ib.usp.br/doku.php?id=01_curso_atual:exercicios4),\n  automatically graded in [notaR](http://notar.ib.usp.br), in R.\n:::\n\n::: {.callout-note}\n## The data: ATLANTIC BIRD TRAITS\n\n**ATLANTIC BIRD TRAITS** [@rodrigues2019atlantic] compiles morphological measurements\nof birds from the Atlantic forests of South America: 72 483 records, gathered from\nmuseum collections, ringing projects and the literature between 1820 and 2018, by 179\nauthors. Its data paper states that there are no copyright or proprietary restrictions\non its use, and asks that it be cited when used in publications or teaching — as here.\n\n`data/atlantic_bird_traits.csv` keeps **all** records and 21 of the original 83\ncolumns, with their original names and codes. Nothing is cleaned: finding the problems\nis the point. `scripts/prepare_birds.jl` documents how the subset was made from the\noriginal file, which is in the paper's supporting information.\n:::\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nusing TidierData\nusing DataFrames, CSV\nusing Statistics, StatsBase\nusing GLM, RDatasets, Distributions\nusing CairoMakie\n\nCairoMakie.activate!(type = \"png\")\nbird_file = joinpath(\"..\", \"data\", \"atlantic_bird_traits.csv\")\n```\n\n::: {#setup-07 .cell-output .cell-output-display execution_count=1}\n```\n\"../data/atlantic_bird_traits.csv\"\n```\n:::\n:::\n\n\n\n\n\n::: {.callout-note .exercise}\n## Exercises in this chapter\n\nThe answers are numbers computed from the bird data. Start each session with:\n\n```julia\ninclude(\"exercises/check.jl\")\nusing TidierData, DataFrames, CSV, Statistics, StatsBase, GLM, Distributions\nbird_file = joinpath(\"data\", \"atlantic_bird_traits.csv\")\n```\n\nThe first section shows how to read the file; the later exercises assume you have read\nit that way, into `birds`, with the columns renamed.\n:::\n\n## First contact: reading the file {#sec-eda-read}\n\nRead the file as it comes and look at the type of each column:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nraw = CSV.read(bird_file, DataFrame)\nsize(raw)\n```\n\n::: {#read-naive .cell-output .cell-output-display execution_count=1}\n```\n(72483, 21)\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfirst(describe(raw, :eltype, :nmissing), 8)\n```\n\n::: {#types-naive .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|ccc}\n\t& variable & eltype & nmissing\\\\\n\t\\hline\n\t& Symbol & DataType & Int64\\\\\n\t\\hline\n\t1 & ID\\_ABT & String7 & 0 \\\\\n\t2 & Order & String31 & 0 \\\\\n\t3 & Family & String31 & 0 \\\\\n\t4 & Binomial & String31 & 0 \\\\\n\t5 & Body\\_mass.g. & String7 & 0 \\\\\n\t6 & Wing\\_length.mm. & String7 & 0 \\\\\n\t7 & Tail\\_length.mm. & String7 & 0 \\\\\n\t8 & Tarsus\\_length.mm. & String7 & 0 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\nBody mass, wing length, tail length: all read as **text** (`String`), and not one value\nis missing. The reason is in the file itself — missing values are written as the two\nletters `NA`, which `CSV.jl` does not treat as missing by default. One non-number in a\ncolumn makes the whole column text. Tell `CSV.read` which code means missing:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nbirds = CSV.read(bird_file, DataFrame; missingstring = \"NA\")\nfirst(describe(birds, :eltype, :nmissing), 8)\n```\n\n::: {#read-na .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|ccc}\n\t& variable & eltype & nmissing\\\\\n\t\\hline\n\t& Symbol & Type & Int64\\\\\n\t\\hline\n\t1 & ID\\_ABT & String7 & 0 \\\\\n\t2 & Order & String31 & 0 \\\\\n\t3 & Family & String31 & 0 \\\\\n\t4 & Binomial & String31 & 0 \\\\\n\t5 & Body\\_mass.g. & Union\\{Missing, Float64\\} & 11664 \\\\\n\t6 & Wing\\_length.mm. & Union\\{Missing, Float64\\} & 51134 \\\\\n\t7 & Tail\\_length.mm. & Union\\{Missing, Float64\\} & 26183 \\\\\n\t8 & Tarsus\\_length.mm. & Union\\{Missing, Float64\\} & 50742 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\n::: {.r-equivalent}\n**In R**\n\n`read.csv` treats `\"NA\"` as missing by default, so in R this problem would pass\nunnoticed. Here it is visible: a numeric column that arrives as text is the first sign\nthat the file uses a missing-value code you have not declared. Other common codes are\n`\"\"`, `\"-\"`, `\".\"`, `-999` and `99999`; `missingstring` also accepts a vector of them.\n:::\n\nThe column names mix units, dots and capitals, like `Body_mass.g.`. They are awkward to\ntype and Tidier macros cannot use them directly. Rename them once, at the start:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nrename!(birds,\n    \"ID_ABT\" => :id, \"Order\" => :order, \"Family\" => :family, \"Binomial\" => :species,\n    \"Body_mass.g.\" => :mass_g, \"Wing_length.mm.\" => :wing_mm,\n    \"Tail_length.mm.\" => :tail_mm, \"Tarsus_length.mm.\" => :tarsus_mm,\n    \"Bill_length.mm.\" => :bill_mm, \"Age\" => :age, \"Sex\" => :sex, \"Status\" => :status,\n    \"Recapture\" => :recapture, \"Ring\" => :ring,\n    \"Latitude_decimal_degrees\" => :lat, \"Longitude_decimal_degrees\" => :lon,\n    \"Altitude\" => :altitude, \"Year\" => :year, \"Main_researcher\" => :source,\n    \"Outside.range\" => :outside_range, \"Obs.spp\" => :species_note)\n\nnames(birds)\n```\n\n::: {#rename .cell-output .cell-output-display execution_count=1}\n```\n21-element Vector{String}:\n \"id\"\n \"order\"\n \"family\"\n \"species\"\n \"mass_g\"\n \"wing_mm\"\n \"tail_mm\"\n \"tarsus_mm\"\n \"bill_mm\"\n \"age\"\n ⋮\n \"recapture\"\n \"ring\"\n \"lat\"\n \"lon\"\n \"altitude\"\n \"year\"\n \"source\"\n \"outside_range\"\n \"species_note\"\n```\n:::\n:::\n\n\n\n::: {.callout-note .exercise}\n## Your turn 7.1 — How many birds were weighed?\n\nHow many records have a body mass? Pass the number to `check(\"7.1\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\n`count(!ismissing, v)` counts the non-missing values of a vector. It only means\nsomething once the file has been read with `missingstring = \"NA\"`.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nn_mass = count(!ismissing, birds.mass_g)\n```\n\n::: {#answer-7-1 .cell-output .cell-output-display execution_count=1}\n```\n60819\n```\n:::\n:::\n\n\n\n::: {#answer-7-1-check .cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"7.1\", n_mass)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n:::\n\n\n\n60 819 of 72 483: body mass is the most commonly recorded trait, and still missing for\none record in six.\n:::\n:::\n\n\n\n## Missing, unknown, and inconsistent {#sec-eda-codes}\n\nCategorical columns deserve a table of their levels before anything else:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n(age = countmap(birds.age), sex = countmap(birds.sex))\n```\n\n::: {#levels-age-sex .cell-output .cell-output-display execution_count=1}\n```\n(age = Dict{Union{Missing, String15}, Int64}(String15(\"Juvenile\") => 8708, missing => 4935, String15(\"Adult\") => 52111, String15(\"Unknown\") => 6727, String15(\"Nestling\") => 2), sex = Dict{Union{Missing, String7}, Int64}(String7(\"Female\") => 14586, String7(\"Male\") => 18420, missing => 3072, String7(\"Unknown\") => 36405))\n```\n:::\n:::\n\n\n\nThere are **two kinds of missing** here. `missing` means the information was never\nrecorded; `\"Unknown\"` means someone looked at the bird and could not tell. They are not\nthe same thing: a study of sex ratios should count the unknowns, but not the unrecorded.\n\nOther columns disagree with themselves about spelling:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n(recapture = countmap(birds.recapture), outside_range = countmap(birds.outside_range))\n```\n\n::: {#levels-case .cell-output .cell-output-display execution_count=1}\n```\n(recapture = Dict{Union{Missing, String3}, Int64}(String3(\"Yes\") => 8556, missing => 33682, String3(\"no\") => 30245), outside_range = Dict{String3, Int64}(\"Yes\" => 2725, \"no\" => 69758))\n```\n:::\n:::\n\n\n\n`\"no\"` and `\"Yes\"`: the capitalization differs between levels. Here it is harmless,\nbecause each level has only one spelling, but a single `\"yes\"` somewhere would create a\nthird level that grouping would treat as different. Normalizing is cheap:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nbirds.recapture     = passmissing(lowercase).(birds.recapture)\nbirds.outside_range = lowercase.(birds.outside_range)\nunique(birds.recapture)\n```\n\n::: {#normalize .cell-output .cell-output-display execution_count=1}\n```\n3-element Vector{Union{Missing, String}}:\n \"no\"\n missing\n \"yes\"\n```\n:::\n:::\n\n\n\n`passmissing(f)` applies `f` to values and leaves `missing` alone.\n\n::: {.callout-note .exercise}\n## Your turn 7.2 — How often can sex be told?\n\nAmong records where sex was **recorded** (not `missing`), what proportion were sexed as\n`\"Male\"` or `\"Female\"`? Pass it to `check(\"7.2\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\nKeep the non-missing values with `collect(skipmissing(birds.sex))`, then take the mean\nof `in((\"Male\", \"Female\")).(...)`.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsex_recorded = collect(skipmissing(birds.sex))\np_sexed = mean(in((\"Male\", \"Female\")).(sex_recorded))\n```\n\n::: {#answer-7-2 .cell-output .cell-output-display execution_count=1}\n```\n0.47551540822059907\n```\n:::\n:::\n\n\n\n::: {#answer-7-2-check .cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"7.2\", p_sexed)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n:::\n\n\n\nLess than half: many Atlantic forest passerines cannot be sexed in the hand. Any\nanalysis by sex is an analysis of a non-random half of the data.\n:::\n:::\n\n\n\n## Structure: what is a replicate? {#sec-eda-structure}\n\nA row is a record, but records are not independent observations. They are grouped in\nseveral ways at once.\n\n**By species.** The records are very unequally spread:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nper_species = sort(combine(groupby(birds, :species), nrow => :n), :n, rev = true)\n\n(names = nrow(per_species),\n top_five = first(per_species, 5),\n with_one_record = count(==(1), per_species.n))\n```\n\n::: {#per-species .cell-output .cell-output-display execution_count=1}\n```\n(names = 780, top_five = 5×2 DataFrame\n Row │ species                   n     \n     │ String31                  Int64 \n─────┼─────────────────────────────────\n   1 │ Chiroxiphia caudata        1857\n   2 │ Turdus albicollis          1686\n   3 │ Trichothraupis melanops    1493\n   4 │ Turdus leucomelas          1475\n   5 │ Basileuterus culicivorus   1419, with_one_record = 68)\n```\n:::\n:::\n\n\n\n780 names — some identified only to genus, such as `Elaenia sp.` — while the data paper\nreports 711 species. Before counting species, decide what counts as one. The ten most\nrecorded species hold a fifth of all records; 68 names appear once.\n\n**By individual.** A ringed bird caught again appears again:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nringed = dropmissing(birds[:, [:ring, :species]], :ring)\nper_ring = combine(groupby(ringed, :ring), :species => (s -> length(unique(s))) => :n_species,\n                   nrow => :n)\nfirst(sort(per_ring[per_ring.n_species .> 1, :], :n, rev = true), 6)\n```\n\n::: {#rings .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|ccc}\n\t& ring & n\\_species & n\\\\\n\t\\hline\n\t& String31 & Int64 & Int64\\\\\n\t\\hline\n\t1 & BRD & 25 & 31 \\\\\n\t2 & VRD & 24 & 27 \\\\\n\t3 & AZD & 21 & 26 \\\\\n\t4 & AZE & 22 & 24 \\\\\n\t5 & IND1 & 4 & 15 \\\\\n\t6 & BRE & 14 & 14 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\nSome \"rings\" are shared by more than twenty species. They are not ring numbers but\n**colour-band codes** such as `BRD` or `BLUE RIGHT`, which many birds carry. A naive\ncount of recaptures would take all those birds for one individual.\n\n**By source and method.** Each record comes from one of 65 main researchers, and from\nlive birds or museum skins, over two centuries:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncombine(groupby(dropmissing(birds[:, [:status, :year]]), :status),\n        nrow => :n, :year => minimum => :first, :year => median => :median,\n        :year => maximum => :last)\n```\n\n::: {#status-year .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|ccccc}\n\t& status & n & first & median & last\\\\\n\t\\hline\n\t& String7 & Int64 & Int64 & Float64 & Int64\\\\\n\t\\hline\n\t1 & live & 57862 & 1990 & 2010.0 & 2018 \\\\\n\t2 & museum & 11152 & 1820 & 2007.0 & 2017 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\nEach of these groupings can make records from the same group more alike than records\nfrom different groups — the dependence that the mixed models of @sec-mixed-models\naccount for. Exploring the structure tells you which grouping terms a model needs.\n\n::: {.callout-note .exercise}\n## Your turn 7.3 — How many birds were caught twice?\n\nCount the individuals recorded more than once: rings that appear in more than one\nrecord **of the same species**, ignoring ring codes made only of letters (colour-band\ncodes). Pass the number to `check(\"7.3\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\nDrop the letter-only codes with `occursin(r\"^[A-Za-z]+$\", ring)`, which is `true` for\nthem. Then group by `ring` **and** `species`, count rows, and count the groups with more\nthan one.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nreal_rings = ringed[.!occursin.(r\"^[A-Za-z]+$\", ringed.ring), :]\nper_bird = combine(groupby(real_rings, [:ring, :species]), nrow => :n)\nn_recaptured = count(>(1), per_bird.n)\n```\n\n::: {#answer-7-3 .cell-output .cell-output-display execution_count=1}\n```\n4503\n```\n:::\n:::\n\n\n\n::: {#answer-7-3-check .cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"7.3\", n_recaptured)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n:::\n\n\n\nAbout 4 500 birds contribute two records or more, one of them up to 43. Treating their\nrecords as independent would overstate the sample size — and the colour codes would\nhave added 27 false \"individuals\" to the count.\n:::\n:::\n\n\n\n## Distributions {#sec-eda-distributions}\n\nBody mass across all birds spans three orders of magnitude, from hummingbirds to large\nseabirds. On a linear scale almost everything piles up at the left; on a log scale the\nshape becomes visible:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nmasses = collect(skipmissing(birds.mass_g))\n\nfig = Figure(size = (860, 340))\nax1 = Axis(fig[1, 1], xlabel = \"Body mass (g)\", ylabel = \"Records\", title = \"(a) Linear\")\nhist!(ax1, masses, bins = 60, color = (:steelblue, 0.7))\nax2 = Axis(fig[1, 2], xlabel = \"Body mass (g, log scale)\", title = \"(b) Logarithmic\",\n           xscale = log10)\nhist!(ax2, masses, bins = 10 .^ range(0, 3.6, length = 60), color = (:steelblue, 0.7))\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Body mass of all weighed birds, on a linear (a) and a logarithmic (b) scale.](07-exploratory_files/figure-pdf/fig-mass-scales-output-1.png){#fig-mass-scales width=860 height=340 fig-pos='H'}\n:::\n:::\n\n\n\nSizes, areas and concentrations are bounded at zero and grow multiplicatively, so they\nare usually right-skewed and closer to symmetric on a log scale. That is why models of\nsuch variables so often use their logarithm.\n\nWithin one species the picture is different. For the white-necked thrush (*Turdus\nalbicollis*), one of the most recorded species, compare the distribution with a normal\ncurve of the same mean and standard deviation:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nthrush = collect(skipmissing(birds.mass_g[birds.species .== \"Turdus albicollis\"]))\nμ, σ = mean(thrush), std(thrush)\n\nfig = Figure(size = (860, 340))\nax1 = Axis(fig[1, 1], xlabel = \"Body mass (g)\", ylabel = \"Density\", title = \"(a) Histogram\")\nhist!(ax1, thrush, bins = 40, normalization = :pdf, color = (:seagreen, 0.6))\nxs = range(minimum(thrush), maximum(thrush), length = 200)\nlines!(ax1, xs, @.(exp(-(xs - μ)^2 / (2σ^2)) / (σ * sqrt(2π))), color = :black)\n\nax2 = Axis(fig[1, 2], xlabel = \"Normal quantiles\", ylabel = \"Body mass (g)\",\n           title = \"(b) QQ plot\")\nn = length(thrush)\nz = quantile.(Normal(), ((1:n) .- 0.5) ./ n)\nscatter!(ax2, z, sort(thrush), color = (:seagreen, 0.5), markersize = 5)\nablines!(ax2, μ, σ, color = :black, linestyle = :dash)\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Body mass of *Turdus albicollis*: histogram with a normal curve of the same mean and standard deviation (a), and a QQ plot against the normal (b).](07-exploratory_files/figure-pdf/fig-thrush-output-1.png){#fig-thrush width=860 height=340 fig-pos='H'}\n:::\n:::\n\n\n\nClose to normal in the middle, with a few birds far lighter or heavier than the rest —\nvisible as the points that leave the line at both ends of the QQ plot. Those tails are\nthe subject of the next section.\n\n::: {.callout-note .exercise}\n## Your turn 7.4 — Mean or median?\n\nCompute the median and the mean body mass of *Turdus albicollis* and pass them, in that\norder, as a vector to `check(\"7.4\", ...)`. Which is less affected by the extreme birds?\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\n`thrush` above already holds the masses. `[median(x), mean(x)]` builds the vector.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nthrush_centre = [median(thrush), mean(thrush)]\n```\n\n::: {#answer-7-4 .cell-output .cell-output-display execution_count=1}\n```\n2-element Vector{Float64}:\n 66.0\n 66.74542818610924\n```\n:::\n:::\n\n\n\n::: {#answer-7-4-check .cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"7.4\", thrush_centre)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n:::\n\n\n\n66 and 66.7 g: nearly equal, as expected for a roughly symmetric distribution. The\nmedian ignores how extreme the tails are; the mean is pulled by them. With a few\nrecords at 26 g or 114 g, the mean moves slightly; with the gross errors of the next\nsection, it would move much more.\n:::\n:::\n\n\n\n## Errors and outliers {#sec-eda-outliers}\n\nAn overall histogram cannot show an error in a 14 g bird recorded as 1 240 g: 1 240 g\nis a perfectly ordinary mass for a large bird. Outliers in trait data are outliers\n**relative to the species**. A simple, robust flag compares each mass with the median\nof its species:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nweighed = dropmissing(birds[:, [:species, :mass_g, :age, :status, :source]], :mass_g)\nweighed = transform(groupby(weighed, :species),\n                    :mass_g => median => :species_median, nrow => :n_species)\nweighed.ratio = weighed.mass_g ./ weighed.species_median\n\nsuspicious = sort(weighed[(weighed.n_species .>= 10) .& (weighed.ratio .> 3), :],\n                  :ratio, rev = true)\nfirst(suspicious[:, [:species, :mass_g, :species_median, :ratio, :age, :status]], 8)\n```\n\n::: {#mass-ratio .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|cccccc}\n\t& species & mass\\_g & species\\_median & ratio & age & status\\\\\n\t\\hline\n\t& String31 & Float64 & Float64 & Float64 & String15? & String7?\\\\\n\t\\hline\n\t1 & Thlypopsis sordida & 1240.0 & 14.0 & 88.5714 & Unknown & museum \\\\\n\t2 & Thlypopsis sordida & 1070.0 & 14.0 & 76.4286 & Unknown & museum \\\\\n\t3 & Corythopis delalandi & 214.0 & 15.0 & 14.2667 & Adult & live \\\\\n\t4 & Tityra cayana & 940.0 & 73.0 & 12.8767 & Juvenile & museum \\\\\n\t5 & Tityra cayana & 840.0 & 73.0 & 11.5068 & Juvenile & museum \\\\\n\t6 & Platyrinchus mystaceus & 102.0 & 9.0 & 11.3333 & \\emph{missing} & \\emph{missing} \\\\\n\t7 & Thalurania glaucopis & 50.0 & 4.5 & 11.1111 & Adult & live \\\\\n\t8 & Phaethornis eurynome & 55.0 & 5.0 & 11.0 & Adult & live \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\nThe top of the list shows several kinds of problem:\n\n- *Thlypopsis sordida*, a 14 g tanager, recorded at more than 1 kg: almost certainly a\n  data-entry error, perhaps a misplaced decimal separator or a wrong unit.\n- Several masses about **ten times** the species median — 102 g for a 9 g flycatcher,\n  50 g for a 4.5 g hummingbird: the signature of a shifted decimal point.\n- Heavy juvenile *Tityra cayana* in a museum collection: possibly errors, possibly a\n  mislabelled specimen. Only the source can tell.\n\nNow the other tail:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfirst(sort(weighed[(weighed.n_species .>= 10) .& (weighed.ratio .< 1/3), :], :ratio)[:,\n      [:species, :mass_g, :species_median, :ratio, :age, :status]], 6)\n```\n\n::: {#mass-ratio-low .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|cccccc}\n\t& species & mass\\_g & species\\_median & ratio & age & status\\\\\n\t\\hline\n\t& String31 & Float64 & Float64 & Float64 & String15? & String7?\\\\\n\t\\hline\n\t1 & Crypturellus parvirostris & 8.5 & 185.0 & 0.0459459 & Unknown & museum \\\\\n\t2 & Aramides saracura & 22.5 & 346.0 & 0.0650289 & Unknown & museum \\\\\n\t3 & Aramides saracura & 22.5 & 346.0 & 0.0650289 & Juvenile & museum \\\\\n\t4 & Aramides saracura & 24.0 & 346.0 & 0.0693642 & Unknown & museum \\\\\n\t5 & Aramides saracura & 24.0 & 346.0 & 0.0693642 & Juvenile & museum \\\\\n\t6 & Asio clamator & 34.5 & 470.0 & 0.0734043 & Unknown & museum \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\nHere some of the \"outliers\" are real. A 24 g slaty-breasted wood-rail (*Aramides\nsaracura*, median 346 g) marked as juvenile is plausibly a chick. Deleting it would\nremove a real bird; keeping it in an analysis of adult size would distort it.\n\n::: {.callout-important}\n## Flag, don't delete\n\nA statistical rule can only say that a value is unusual, never that it is wrong. Flag\nsuspicious values, look at them one by one, go back to the source where you can, and\ndecide — and write down what you decided and why, in code, so that the decision can be\nreviewed. For many analyses the right choice is to restrict the data to what the\nquestion is about (adults, say) rather than to remove individual points.\n:::\n\nThe data also carry a quieter problem, **precision**. Most masses are whole numbers:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nmean(weighed.mass_g .== round.(weighed.mass_g))\n```\n\n::: {#precision .cell-output .cell-output-display execution_count=1}\n```\n0.7217974646080995\n```\n:::\n:::\n\n\n\n72% of masses are integers, which means many were weighed to the nearest gram. For a\n3 g hummingbird, rounding to the gram is an error of up to 17%; for a thrush, under 1%.\nPrecision that varies with the size of the animal is easy to miss and worth knowing\nbefore you compare small species.\n\n::: {.callout-note .exercise}\n## Your turn 7.5 — How many suspicious masses?\n\nCount the records whose mass is more than 3 times, or less than a third of, the median\nof their species, among species with at least 10 weighed records. Pass the number to\n`check(\"7.5\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\n`weighed` already has `ratio` and `n_species`. Combine the conditions with `.&` and\n`.|`, and count the `true`s with `count`.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nn_suspicious = count((weighed.n_species .>= 10) .&\n                     ((weighed.ratio .> 3) .| (weighed.ratio .< 1/3)))\n```\n\n::: {#answer-7-5 .cell-output .cell-output-display execution_count=1}\n```\n291\n```\n:::\n:::\n\n\n\n::: {#answer-7-5-check .cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"7.5\", n_suspicious)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n:::\n\n\n\n291 of about 60 000 weighed records, 0.5%: few, but enough to wreck a species mean.\nThe threshold of 3 is a choice, not a rule; with 2 you would flag more than twice as\nmany.\n:::\n:::\n\n\n\n## Relationships and collinearity {#sec-eda-collinearity}\n\nMorphological traits go together: big birds have long wings, long tails, long legs and\nlong bills. To see how strongly, summarize each species by the median of each trait —\nthe median, because of the outliers above — and compare species:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ntraits = [:mass_g, :wing_mm, :tail_mm, :tarsus_mm, :bill_mm]\nmedian_or_missing(x) = (v = collect(skipmissing(x)); isempty(v) ? missing : median(v))\n\nby_species = dropmissing(combine(groupby(birds, :species),\n                                 [t => median_or_missing => t for t in traits]...))\nlog_traits = DataFrame(log.(Matrix(by_species[:, traits])), traits)\n\nnrow(by_species)\n```\n\n::: {#species-traits .cell-output .cell-output-display execution_count=1}\n```\n538\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nround.(cor(Matrix(log_traits)); digits = 2)\n```\n\n::: {#correlation-matrix .cell-output .cell-output-display execution_count=1}\n```\n5×5 Matrix{Float64}:\n 1.0   0.93  0.71  0.81  0.72\n 0.93  1.0   0.77  0.72  0.64\n 0.71  0.77  1.0   0.56  0.5\n 0.81  0.72  0.56  1.0   0.64\n 0.72  0.64  0.5   0.64  1.0\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nlabels = [\"log mass\", \"log wing\", \"log tail\", \"log tarsus\", \"log bill\"]\nfig = Figure(size = (820, 820))\nfor i in 1:5, j in 1:5\n    ax = Axis(fig[i, j], xlabel = i == 5 ? labels[j] : \"\", ylabel = j == 1 ? labels[i] : \"\",\n              xticklabelsvisible = i == 5, yticklabelsvisible = j == 1 && i != 1)\n    if i == j                  # diagonal: the distribution of each trait (counts)\n        hist!(ax, log_traits[:, i], bins = 25, color = (:grey60, 0.8))\n    else\n        scatter!(ax, log_traits[:, j], log_traits[:, i], markersize = 3,\n                 color = (:steelblue, 0.5))\n    end\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![Species medians of five traits, on log scales, one point per species. Off the diagonal, each panel shows one pair of traits; on the diagonal, the distribution of each trait.](07-exploratory_files/figure-pdf/fig-pairs-output-1.png){#fig-pairs width=820 height=820 fig-pos='H'}\n:::\n:::\n\n\n\nMass and wing length are almost a single variable across species. If both entered a\nmodel as predictors, the model could not tell their effects apart: the estimates would\nbe unstable and their standard errors large. The **variance inflation factor** measures\nthis. For each predictor, regress it on all the others; with $R^2$ from that\nregression, $\\text{VIF} = 1 / (1 - R^2)$:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfunction vif(df, col)\n    others = setdiff(propertynames(df), [col])\n    f = Term(col) ~ sum(Term.(others))\n    return 1 / (1 - r2(lm(f, df)))\nend\n\nDataFrame(trait = traits, vif = round.([vif(log_traits, t) for t in traits]; digits = 1))\n```\n\n::: {#vif .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|cc}\n\t& trait & vif\\\\\n\t\\hline\n\t& Symbol & Float64\\\\\n\t\\hline\n\t1 & mass\\_g & 11.9 \\\\\n\t2 & wing\\_mm & 9.7 \\\\\n\t3 & tail\\_mm & 2.5 \\\\\n\t4 & tarsus\\_mm & 3.0 \\\\\n\t5 & bill\\_mm & 2.1 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\n@zuur2010protocol use a cut-off of 3; other authors use 5 or 10. Mass and wing length\nare above all of them. The usual responses are\nto keep only one of each collinear group, to combine them (a size index), or to ask a\nquestion that does not need them separately.\n\n::: {.callout-note .exercise}\n## Your turn 7.6 — Mass and wing\n\nWhat is the correlation between log body mass and log wing length across species, using\nthe species medians above? Pass it to `check(\"7.6\", ...)`.\n\n::: {.callout-tip collapse=\"true\"}\n## Hint\n\n`cor(x, y)` on two columns of `log_traits`.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Solution\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nr_mass_wing = cor(log_traits.mass_g, log_traits.wing_mm)\n```\n\n::: {#answer-7-6 .cell-output .cell-output-display execution_count=1}\n```\n0.9326447165263583\n```\n:::\n:::\n\n\n\n::: {#answer-7-6-check .cell execution_count=1}\n``` {.julia .cell-code}\ncheck(\"7.6\", r_mass_wing)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n✓ Correct!\n```\n:::\n:::\n\n\n\nAbout 0.93. Across species, these two traits carry almost the same information.\nWithin a species it is much weaker — about 0.25 among individual *Turdus albicollis* —\nbecause individuals of one species vary little in size: collinearity depends on the\nscale of the question.\n:::\n:::\n\n\n\n## Why the plots: the Anscombe quartet {#sec-anscombe}\n\nSummaries are not a substitute for looking. @anscombe1973graphs built four small data\nsets with the same means, variances, correlations and regression lines:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nanscombe = dataset(\"datasets\", \"anscombe\")\nDataFrame(set = 1:4,\n          mean_x = [mean(anscombe[:, \"X$i\"]) for i in 1:4],\n          mean_y = [round(mean(anscombe[:, \"Y$i\"]); digits = 2) for i in 1:4],\n          cor_xy = [round(cor(anscombe[:, \"X$i\"], anscombe[:, \"Y$i\"]); digits = 3) for i in 1:4])\n```\n\n::: {#anscombe-stats .cell-output .cell-output-display execution_count=1}\n```{=tex}\n\\begin{tabular}{r|cccc}\n\t& set & mean\\_x & mean\\_y & cor\\_xy\\\\\n\t\\hline\n\t& Int64 & Float64 & Float64 & Float64\\\\\n\t\\hline\n\t1 & 1 & 9.0 & 7.5 & 0.816 \\\\\n\t2 & 2 & 9.0 & 7.5 & 0.816 \\\\\n\t3 & 3 & 9.0 & 7.5 & 0.816 \\\\\n\t4 & 4 & 9.0 & 7.5 & 0.817 \\\\\n\\end{tabular}\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfig = Figure(size = (760, 560))\nfor i in 1:4\n    x, y = anscombe[:, \"X$i\"], anscombe[:, \"Y$i\"]\n    ax = Axis(fig[(i - 1) ÷ 2 + 1, (i - 1) % 2 + 1], title = \"Set $i\",\n              limits = (3, 20, 3, 14))\n    scatter!(ax, x, y, color = :steelblue)\n    b = coef(lm(@formula(y ~ x), DataFrame(; x, y)))\n    ablines!(ax, b[1], b[2], color = :darkorange)\nend\nfig\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![The Anscombe quartet: four data sets with the same summary statistics and the same least-squares line.](07-exploratory_files/figure-pdf/fig-anscombe-output-1.png){#fig-anscombe width=760 height=560 fig-pos='H'}\n:::\n:::\n\n\n\nThe first looks like what a linear model assumes. The second is a curve. In the third\none point pulls the line away from an otherwise perfect relationship. In the fourth the\nwhole slope depends on a single observation. Only the plots show it.\n\n## Challenges {.unnumbered}\n\n1. Plot the coordinates of all records (`lon`, `lat`) and colour them by\n   `outside_range`. Are the records flagged as outside the species' range where you\n   would expect? Are there points outside the Atlantic forest region altogether?\n2. Male and female *Chiroxiphia caudata* (blue manakin) differ strikingly in plumage.\n   Do they differ in mass? Compare the distributions, not only the medians, and decide\n   what to do with records of `\"Unknown\"` sex.\n3. Repeat the outlier rule of @sec-eda-outliers for wing length. Are the species with\n   suspicious wings the same as those with suspicious masses? What would that tell you\n   about the source of the errors?\n\n",
    "supporting": [
      "07-exploratory_files/figure-pdf"
    ],
    "filters": []
  }
}